/* ============================================================
   PORTFOLIO CONTENT — edit this file to update the site.
   Images live in assets/img/<project>/. First image = card thumbnail.
   ============================================================ */
window.PORTFOLIO = {
  profile: {
    name: 'Akshay Patil',
    siteTitle: 'Engineering Portfolio',
    eyebrow: 'Aerospace Engineering · Georgia Tech',
    tagline: 'Mechanical design, robotics, and UAVs — the projects behind the resume.',
    blurb: 'I design and build things that move: competition robots, UAV airframes, launchers, rockets, and the CAD workflows that make iterating on them fast. This site is the long-form companion to my resume — the failures, redesigns, and numbers that don\'t fit on one page.',
    resume: 'assets/AkshayPatil_Resume.pdf',
    cta: [
      { label: 'View projects', href: '#projects' },
      { label: 'Resume (PDF)', href: 'assets/AkshayPatil_Resume.pdf', external: true },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/akshaypatil08', external: true },
    ],
    stats: [
      { value: 'Finalist', label: '2026 FIRST Championship alliance' },
      { value: '#1', label: 'intl. rank, FTC 7172 (2021–22)' },
      { value: '5 yrs', label: 'Fusion 360 / Onshape / SolidWorks' },
      { value: 'Part 107', label: 'FAA remote pilot' },
    ],
    contactBlurb: 'Open to internships and research in mechanical design, robotics, and UAS. Fastest way to reach me is email.',
    links: [
      { label: 'akshaypat08@gmail.com', href: 'mailto:akshaypat08@gmail.com' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/akshaypatil08' },
      { label: 'GitHub', href: 'https://github.com/Randomfalcon124' },
      { label: 'FTC 7172', href: 'https://ftc7172.org' },
    ],
  },

  /* ---------------- PROJECTS ---------------- */
  projects: [
    {
      id: 'dual-arm-robot',
      title: '"Phoenix" — Dual-Arm Turret Robot, FTC Power Play',
      date: '2022 – 2023',
      role: 'Lead designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Worm gearboxes', 'Rack & pinion', 'Turret', 'Inverse kinematics', 'Double-helical gears', 'Misumi slides', 'HuskyLens'],
      summary: 'Two three-pivot arms on worm-gear turrets, riding a drivetrain that splits in half on linear slides: 13 ft of reach, no transfer, ~4 s cycles, and all ten cones in autonomous. Worlds division finalist and Innovate Award winner.',
      facts: [
        { label: 'Team', value: 'FTC 7172 Technical Difficulties' },
        { label: 'Result', value: 'Worlds Ochoa Division Finalist · Innovate Award (RTX)' },
        { label: 'Reach', value: '13 ft — 5 ft drivetrain split + two 4 ft arms' },
        { label: 'Season', value: 'TX State Finalist · TX-North Regional champion (6–0) · np-OPR #10 of 5,671' },
      ],
      sections: [
        { heading: 'Problem', text: 'Power Play scored cones on poles of varying height. Our first robot, "Valkyrie", used a horizontal intake extension with grabbers, a transfer to a scoring grabber, and a 350° turret with gantry on a vertical lift. It went 2-3-0 at its first event in November; the handoff was slow and inconsistent, autonomous goals were out of reach, and it could not adapt as we moved around the field for ownership points. We started over.' },
        { heading: 'Design', bullets: [
          'Two arms ("E" and "C", named for the hub each is wired to), each on a worm-gear turret with 270° of rotation, a first pivot on an industrial worm gearbox with 150° range and a counter-spring, a servo-driven cascading linear extension on two rack-and-pinion assemblies, and a third pivot that keeps the grabber parallel to the ground and can flip a cone to score backwards.',
          'One arm intakes while the other scores, so there is no transfer and cycle time halves to about 4 s. From one "golden spot" in front of the substation the robot reaches ten junctions.',
          'Grabbers: double-helical gears for minimum backlash, surgical tubing inside for grip, a funnel-shaped interior, and enough over-extension to sit outside the substation and grab immediately. Linkage versions slipped on curved ends or did not fit in 18 in. A Delrin guide plate under the grabber aligns it to the pole for autonomous.',
          'Drivetrain: GoBilda Strafer-based chassis that splits into two halves on 300 mm Misumi slides — about 5 ft end to end — with a center lock that holds it together when collapsed to 18×18 in. Ground clearance was cut to 0.3 in for a low center of gravity when the arms are out.',
        ]},
        { heading: 'Iteration', text: 'The first two-arm robot used a "bent arm" with an elbow as the second pivot. It had reach and speed but little control: the 4 ft arms tangled with each other and hit field elements, and since the elbow was servo-driven we only knew its target, never its actual position or velocity — one collision broke an arm. Replacing the elbow with the rack-and-pinion extension put the main servos and motors on different axes and made the arm profilable. Delrin couplers on the first-pivot worm gearbox stripped, so we moved to GoBilda REX shafts and a JB-welded metal adapter to remove backlash.' },
        { heading: 'Controls', bullets: [
          'Inverse kinematics: the driver (or autonomous) supplies turret angle, first-pivot angle, and extension length; code resolves servo and motor positions and holds the third pivot level.',
          'Absolute linear potentiometers on the turret and first pivot give a zero at opmode start; since the hubs read them non-linearly, a calibration sweep builds a lookup table from encoder position to potentiometer voltage.',
          'Motion profiling for big moves: retract, pitch pivot 1 toward the ceiling, turn the turret, then lower and extend — so two 4 ft arms never cross.',
          'HuskyLens on each arm detects poles; a drivetrain camera reads the signal sleeve.',
        ]},
        { heading: 'Outcome', text: 'Phoenix debuted Jan 14 at 5-0-0, won the NTX Regional Championship with the Innovate Award, and reached the Ochoa Division Finals at the World Championship, winning the Innovate Award there too. Design reviews along the way came from SpaceX McGregor engineers (arm bounce, passive pole guides), BattleBots winner Jason Bardis (backlash, stabilizing the split drivetrain), and Nokia.' },
      ],
      images: [
        { src: 'assets/img/powerplay/00-phoenix-cutout.jpg', fit: 'contain', alt: 'Phoenix with both arms raised', caption: 'Phoenix — two three-pivot arms, each on a worm-gear turret' },
        { src: 'assets/img/powerplay/00-phoenix-arms-raised-cad.jpg', fit: 'contain', alt: 'Phoenix with both arms raised', caption: 'Phoenix — both arms raised, worm-gear turrets visible' },
        { src: 'assets/img/powerplay/01-arm-cad.jpg', fit: 'contain', alt: 'CAD of the multi-DOF arm with claw', caption: 'Arm linkage + claw — yaw axis and first pivot on worm gearboxes' },
        { src: 'assets/img/powerplay/02-robot-cad.jpg', alt: 'Full robot CAD with arm extended', caption: 'Full assembly, arm extended' },
        { src: 'assets/img/powerplay/03-competition.jpg', alt: 'Robot scoring a cone at competition', caption: 'Scoring at competition' },
        { src: 'assets/img/powerplay/04-built-robot.jpg', alt: 'Built robot with blue 3D-printed parts', caption: 'Original dual-extension build' },
        { src: 'assets/img/powerplay/05-practice-field.jpg', alt: 'Robot on practice field', caption: 'Practice field testing' },
        { src: 'assets/img/powerplay/06-single-arm-cad.jpg', fit: 'contain', alt: 'Single arm with worm gearbox and linear extension', caption: 'One arm: turret, worm-gear first pivot, rack-and-pinion extension, third pivot' },
        { src: 'assets/img/powerplay/08-split-drivetrain-electronics-cad.jpg', fit: 'contain', alt: 'Split drivetrain with electronics', caption: 'Drivetrain halves with hubs — one arm per hub' },
        { src: 'assets/img/powerplay/09-claw-sensor-cad.jpg', fit: 'contain', alt: 'Claw open with distance sensor', caption: 'Double-helical-gear grabber with distance sensor' },
        { src: 'assets/img/powerplay/10-anatomy-cad.jpg', fit: 'contain', alt: 'Labeled overview of Phoenix', caption: 'Annotated overview' },
        { src: 'assets/img/powerplay/11-phoenix-stowed-cad.jpg', fit: 'contain', alt: 'Phoenix stowed, arms folded', caption: 'Collapsed to 18×18 in with center lock' },
        { src: 'assets/img/powerplay/12-arms-splayed-photo.jpg', alt: 'Phoenix with arms fully splayed on the field', caption: 'Full 13 ft span on the practice field' },
        { src: 'assets/img/powerplay/13-scrimmage-photo.jpg', alt: 'Scrimmage in a gym', caption: 'Scrimmage' },
        { src: 'assets/img/powerplay/15-on-field-photo.jpg', alt: 'Phoenix on the Power Play field with arms deployed', caption: 'Arms deployed on the field' },
        { src: 'assets/img/powerplay/17-pivot-extension-cad.jpg', fit: 'contain', alt: 'Arm pivot and rack-and-pinion extension', caption: 'First pivot and cascading rack-and-pinion extension' },
        { src: 'assets/img/powerplay/18-arms-cad.jpg', fit: 'contain', alt: 'Both arms in CAD', caption: 'Both arms, stowed' },
        { src: 'assets/img/powerplay/19-phoenix-build-photo.jpg', alt: 'Phoenix during the build', caption: 'Phoenix, built' },
        { src: 'assets/img/powerplay/16-match-photo.jpg', alt: 'Phoenix during a match', caption: 'Match play' },
      ],
      links: [
        { label: 'Dual-extension test video', href: 'https://drive.google.com/file/d/1bxeMuue50E1q7UYErDWuo7Bku9uY2TJi/view' },
        { label: 'Rack & pinion arm video', href: 'https://drive.google.com/file/d/1WURUEpw_ZJW0e3rRzHhwmaQR8T6Pjgwo/view' },
        { label: 'Behind the Bot (FUN)', href: 'https://youtu.be/HBBmBNJ_7LY' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2022' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/phoenix' },
      ],
    },
    {
      id: 'ftc-7172',
      title: 'FTC 7172 Technical Difficulties — Five Seasons',
      date: '2021 – 2026',
      role: 'Captain & lead mechanical',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Butterfly drivetrain', 'Turret', 'Linear extension', 'Sprung claw', 'Team leadership'],
      summary: 'Lead mechanical engineer across five robots — from a mecanum base with retractable traction wheels to the 2026 World Championship Finalist Alliance.',
      facts: [
        { label: 'My five seasons', value: '245–73–2 in qualification matches · 19 event wins · 63 awards' },
        { label: 'Best finish', value: 'FIRST Championship Finalist Alliance (2026)' },
        { label: 'World np-OPR rank', value: '#1 (2021–22) · #10 (2022–23) · #9 (2023–24)' },
        { label: 'Worlds appearances', value: '4 of 5 seasons — 2022, 2023, 2025, 2026' },
      ],
      sections: [
        { heading: 'Robots', bullets: [
          '2021–22 "Defiant" (Freight Frenzy): mecanum drivetrain with four retractable traction wheels for pushing matches; extending tape-measure turret; belted cascade extension reaching 30 in. Worlds Jemison division rank 2, Championship Think Award 3rd; np-OPR #1 of 4,404 worldwide (FTCScout).',
          '2022–23 "Phoenix" (Power Play): dual-arm turret on an extending drivetrain, 13 ft scoring radius. Worlds Ochoa Division Finalist + Innovate Award. See the dedicated project.',
          '2023–24 "Athena" (Centerstage): tilting belted elevator on lead screws, two-pixel compliant scorer, rail-launched drone. FiT-North Area Champion + Control Award; ftcstats qualifier rank #1.',
          '2024–25 "Nautilus" (Into the Deep): sprung claw designed for wall pickup and passive chamber clipping. Worlds Franklin division rank 14, Connect Award; FiT-North Regional Winner + Control.',
          '2025–26 "Rebound" (Decode): wedge spindexer, sprung-cam hammer, flywheel with telescoping hood on a 200 Hz servo turret — three sorted balls in under half a second. Worlds Goodall Division Winner → FIRST Championship Finalist Alliance.',
        ]},
        { heading: 'Results by season', bullets: [
          '2021–22: 60–5–0. Alabama State champion + Inspire; TX-North Regional champion + Innovate; Worlds Jemison division #2, Think Award 3rd. np-OPR #1 of 4,404.',
          '2022–23: 61–22–0. TX-North Regional champion + Innovate; Texas State Finalist + Connect; Worlds Ochoa Division Finalist + Innovate. np-OPR #10 of 5,671.',
          '2023–24: 41–3–0. Undefeated league play; U² Tournament winner + Inspire; Area Champion + Control; TX State division finalist; Maryland Tech Invitational finalist. np-OPR #9 worldwide, #1 in Texas.',
          '2024–25: 50–18–2. Early Bird winner + Think; FiT-North Regional Champion (captain) + Control; Worlds Franklin division #14, Connect Award.',
          '2025–26: 33–25–0. Regional division finalist; Worlds Goodall Division Winner; FIRST Championship Finalist Alliance.',
        ]},
        { heading: 'Leadership', bullets: [
          'Reviewed 85 applications, ran 40 interviews, and onboarded 13 new members.',
          'Ran a summer design camp with 200+ participants; attendees went on to become 2025 Worlds division winners.',
          'Recovered from grabber and drive-module failures mid-event (Dec 2024) to win from rank 10 of 24.',
          'Set up the team\'s 501(c)(3).',
        ]},
      ],
      images: [
        { src: 'assets/img/ftc7172/01-rebound-2026.jpg', alt: 'Rebound, the 2025-26 Decode robot', caption: '"Rebound" (2025–26 Decode) — World Championship Finalist Alliance' },
        { src: 'assets/img/ftc7172/02-phoenix-2023.jpg', fit: 'contain', alt: 'Phoenix, the 2022-23 Power Play robot', caption: '"Phoenix" (2022–23 Power Play) — dual-arm turret on extending drivetrain' },
        { src: 'assets/img/ftc7172/03-nautilus-2025.jpg', alt: 'Nautilus, the 2024-25 Into the Deep robot', caption: '"Nautilus" (2024–25 Into the Deep) — sprung claw for wall pickup' },
        { src: 'assets/img/ftc7172/04-defiant-2022.jpg', alt: 'Defiant, the 2021-22 Freight Frenzy robot', caption: '"Defiant" (2021–22 Freight Frenzy) — butterfly drivetrain, intl. rank #1' },
      ],
      links: [
        { label: 'ftc7172.org', href: 'https://www.ftc7172.org' },
        { label: 'All stats (FTCScout)', href: 'https://ftcscout.org/teams/7172' },
        { label: 'FIRST blog — 2026 Finalist Alliance', href: 'https://community.firstinspires.org/congratulations-to-our-decode-first-championship-teams' },
        { label: 'YouTube', href: 'https://www.youtube.com/channel/UCAqfGNnORI9ZZcjtNGsgPvQ' },
        { label: 'Behind the Bot — Power Play (FUN)', href: 'https://youtu.be/HBBmBNJ_7LY' },
      ],
    },
    {
      id: 'defiant',
      title: '"Defiant" — Flip-Arm Turret Robot, FTC Freight Frenzy',
      date: '2021 – 2022',
      role: 'Designer & builder',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Master sketches', 'Belt cascade', 'Turret', 'Butterfly drivetrain', 'Tape measure', 'JVN calcs'],
      summary: 'My first full season in Fusion 360: a flipping intake arm that mirrors the robot red-to-blue mid-match, a belted 30 in cascade extension, and a drivetrain that drops four extra torque wheels to win shoving matches.',
      facts: [
        { label: 'Result', value: 'Worlds Jemison div. rank 2 (7–1) · Championship Think Award 3rd' },
        { label: 'Season', value: '60–5–0 quals · 7 event wins · Alabama State + TX-North champions' },
        { label: 'np-OPR', value: '222.5 — #1 of 4,404 teams worldwide' },
        { label: 'Extension', value: '3× 200 mm Misumi slides → 30 in, 0.5 s full stroke' },
        { label: 'Drivetrain', value: '14.2:1 mecanum + retractable traction wheels' },
      ],
      sections: [
        { heading: 'Dual-sided intake arm', text: 'Scoring from the wall with side-depositing slides meant we had to intake from either the red or blue side. Instead of two intakes or rotating the slides, we fixed the elevator and put the intake on an arm that flips over the robot — one mechanism acting as two intakes, and the robot mirrors sides in seconds. JVN calculations put the arm at ~100:1 for sub-0.5 s swings; a REV UltraPlanetary version was scrapped for gearbox slack.' },
        { heading: 'Turret intake', text: 'Silicone-tube intake on an internal 360° turret, feeding a polycarbonate hopper sized for exactly one freight so a second piece gets ejected before it can become a penalty. Power comes through miter gears and chain from the arm channel. The same motor also drives the carousel wheel via a belt, so duck scoring costs no extra actuator.' },
        { heading: 'Horizontal linear extension', text: 'Three 200 mm Misumi slides cascaded with belts on custom 3D-printed pulley mounts: 30 in of reach that fully extends or retracts in about half a second. V1 (mixed 200/300 mm slides) failed on weak mounts and unsupported idlers and did not fit the size box.' },
        { heading: 'Drivetrain', text: 'Bigger robots could shove us off the shared hub. Fix: keep the fast 14.2:1 mecanum base and add four retractable traction wheels that drop only when we need to push back — the "butterfly" drivetrain. Earlier high-clearance chain versions lost tracking precision and suffered encoder interference from motors mounted too close together.' },
        { heading: 'Scoring grippers & capping', bullets: [
          'Custom 3D-printed claws on a two-bar linkage (GoBilda SuperSpeed servo) that hold cubes, balls, and ducks and drop them on any hub level — after a scoring box and a three-point linkage both proved too slow or too weak.',
          'Capping via a servo-driven tape-measure extension with pan/tilt; the magnet concept was discarded because it pulled weighted freight off the hub.',
          'Lesson: capping only pays if it does not cost cycles, so we cap while delivering ducks.',
        ]},
      ],
      images: [
        { src: 'assets/img/defiant/00-defiant-cutout.jpg', fit: 'contain', alt: 'Defiant with tape-measure turret and intake arm', caption: 'Defiant — flip-over intake arm, cascade extension, tape-measure capper' },
        { src: 'assets/img/defiant/02-drivetrain-photo.jpg', alt: 'Built butterfly drivetrain, side view', caption: 'Butterfly drivetrain as built — mecanum pods with retractable traction wheels' },
        { src: 'assets/img/defiant/03-cascade-extension-cad.jpg', alt: 'Cascade linear extension CAD', caption: 'Belted cascade extension — 3× 200 mm slides, 30 in reach' },
        { src: 'assets/img/defiant/04-drivetrain-underside-cad.jpg', alt: 'Drivetrain underside CAD showing motors', caption: 'Underside — motor placement after encoder-interference lesson' },
        { src: 'assets/img/defiant/05-tape-measure-turret-cad.jpg', alt: 'Tape-measure turret spool CAD', caption: 'Tape-measure capping turret — spool, pan and tilt' },
        { src: 'assets/img/defiant/06-intake-bucket-cad.jpg', alt: 'Intake bucket with servo door CAD', caption: 'One-freight hopper with servo door' },
        { src: 'assets/img/defiant/07-extension-motor-cad.jpg', alt: 'Extension module with motor CAD', caption: 'Extension drive module' },
        { src: 'assets/img/defiant/08-robot-front-photo.jpg', alt: 'Robot front with intake', caption: 'Defiant, front' },
        { src: 'assets/img/defiant/09-full-robot-render.jpg', alt: 'Full robot render', caption: 'Full robot render' },
        { src: 'assets/img/defiant/10-worlds-field-photo.jpg', alt: 'Defiant on the World Championship field', caption: 'On the field at the 2022 World Championship' },
        { src: 'assets/img/defiant/12-match-photo.jpg', alt: 'Defiant mid-match with freight', caption: 'Mid-match' },
      ],
      links: [
        { label: 'Defiant reveal video', href: 'https://youtu.be/c_Lumfw_asU' },
        { label: 'Behind the Bot (FUN)', href: 'https://youtu.be/Q2nJBSsAp2c' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2021' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/defiant' },
        { label: 'Team page', href: 'https://www.ftc7172.org' },
      ],
    },
    {
      id: 'nautilus',
      cardImage: 8,
      title: '"Nautilus" — Passive-Claw Specimen Robot, FTC Into the Deep',
      date: '2024 – 2025',
      role: 'Lead designer',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Belted slides', 'Worm gear', 'Passive claw', 'Swyft modules', 'Color sensor', 'Delrin'],
      summary: 'A specimen scorer that grabs and scores with zero actuators — a geared two-way claw with a mechanical hard stop — plus a 2.6 ft belted elevator with a 90° tilt so samples never need a transfer.',
      facts: [
        { label: 'Result', value: 'FiT-North Regional Champion (alliance captain) + Control Award' },
        { label: 'Worlds', value: 'Franklin div. rank 14 (7–3) · Connect Award' },
        { label: 'Season', value: '50–18–2 quals · 5 event wins · np-OPR #8 in Texas' },
        { label: 'Elevator', value: '2.6 ft belted slides with a 90° tilt' },
        { label: 'Auto', value: '6-specimen autonomous' },
      ],
      sections: [
        { heading: 'Specimen scorer', text: 'Early versions were a vertical extension, then a scissor claw with an active latch — three degrees of freedom, slow, unstable when extended backwards. The fix was to remove actuation: a geared passive claw with a 180° lateral pivot grabs a specimen off the wall just by driving into it, and a mechanical hard stop ends claw motion so scoring is pure drive. Claw geometry was tuned (with the math on the page) so the passive action could not shear a servo spline.' },
        { heading: 'Intake', text: 'Four iterations: tri-claw → dual tubing → trapdoor → 3D-printed pincer claw. The pincers open ~3 in to pull from crowds, oscillate between parallel and perpendicular for angled samples, and sit on a 360° pivot. A REV v3 color/distance sensor rejects opposing-alliance samples and triggers automatic drive to the drop position; inverse trigonometry maps joystick motion to claw pose.' },
        { heading: 'Elevator and tilt', text: 'Belted Swyft slides with 2.6 ft of reach into any side of the submersible. The 90° tilt eliminates a sample transfer entirely. A worm-gear tilt was slow and shredded gears, so it moved to spur + pinion; 13.7:1 and 5.2:1 motors could not balance torque and speed at full extension, so a 60:36 reduction on a 5.2:1 motor was used. The extension motor is coaxial to cut tipping and the lift is counter-sprung.' },
        { heading: 'Drivetrain, pushbar, hang', bullets: [
          'Swyft direct-drive modules: more space in the middle of the chassis, quick to swap if one breaks, enough ground clearance to drive over samples.',
          'Servo pushbar shoves pre-set samples into the observation zone during autonomous.',
          'Level-3 hang from separate Delrin hooks on the slides, each on its own servo, fitting inside the corners of the robot.',
        ]},
        { heading: 'Process', text: 'Subsystems were built to be removable and tested individually before integration; a test program exercised each mechanism and an odometry calibration routine reset pose before every match. Timeline: kickoff prototypes in September, Swyft drive and Misumi elevator by October, color-sensor specimen detection in November, 5-specimen auto in December, trapdoor and double-slide elevator in February, L3 hang and pincer claw in March.' },
      ],
      images: [
        { src: 'assets/img/nautilus/01-robot-cad.jpg', alt: 'Nautilus full robot CAD render', caption: 'Nautilus — full assembly' },
        { src: 'assets/img/nautilus/02-elevator-extended-cad.jpg', alt: 'Nautilus with elevator fully extended', caption: 'Elevator at full 2.6 ft extension with 90° tilt' },
        { src: 'assets/img/nautilus/04-specimen-claw-cad.jpg', fit: 'contain', alt: 'Passive specimen claw on vertical slide', caption: 'Passive two-way specimen claw — grabs and scores by driving' },
        { src: 'assets/img/nautilus/03-drivetrain-cad.jpg', fit: 'contain', alt: 'Swyft-module mecanum drivetrain CAD', caption: 'Swyft direct-drive mecanum chassis' },
        { src: 'assets/img/nautilus/05-extension-hooks-cad.jpg', fit: 'contain', alt: 'Extension slides with Delrin hang hooks', caption: 'Slides with Delrin L3 hang hooks' },
        { src: 'assets/img/nautilus/06-carriage-sprocket-cad.jpg', fit: 'contain', alt: 'Slide carriage with sprocket and bearings', caption: 'Slide carriage — sprocket and bearing stack' },
        { src: 'assets/img/nautilus/07-gripper-closeup-cad.jpg', alt: 'Gripper close-up render', caption: 'Pincer intake close-up' },
        { src: 'assets/img/nautilus/08-team-robot-photo.jpg', alt: 'Team with Nautilus at competition', caption: 'Team 7172 with Nautilus' },
        { src: 'assets/img/ftc7172/03-nautilus-2025.jpg', alt: 'Nautilus on the Into the Deep field', caption: 'Nautilus on the field' },
      ],
      links: [
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2024' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/nautilus' },
      ],
    },
    {
      id: 'athena',
      title: '"Athena" — Tilting-Elevator Pixel Robot, FTC Centerstage',
      date: '2023 – 2024',
      role: 'Lead designer',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Misumi slides', 'Lead screws', 'Rack & pinion', 'Over-center linkage', 'TPU', 'Pure Pursuit'],
      summary: 'A compact mecanum robot whose belted elevator rides on lead-screw tilt so it can score any backdrop row without being parallel to it — plus a two-pixel compliant scorer, a rail-launched drone, and a lead-screw hang.',
      facts: [
        { label: 'Result', value: 'Area Champion (6–0) + Control Award · TX State div. finalist · MTI Finalist' },
        { label: 'Season', value: '41–3–0 quals · undefeated through league play · U² Tournament winner + Inspire' },
        { label: 'np-OPR', value: '182.7 — #1 of 732 in Texas, #9 of 6,664 worldwide' },
        { label: 'Elevator', value: '2× 300 mm 3-stage Misumi, 0.5 s stroke' },
      ],
      sections: [
        { heading: 'Drivetrain', text: 'Four 13.7:1 GoBilda motors direct-driving mecanums on custom side plates, sized to clear pixels underneath and thread the trusses and stage door. V1 on the 384 mm GoBilda kit had no mounting room; V2 was 24 mm wider and ran two league meets before it proved slower and harder to maneuver — the final chassis is smaller, lighter (easier hang), and crosses the field in about five seconds.' },
        { heading: 'Intake', text: 'Surgical-tubing intake on a 3.7:1 motor, mechanically limited to two pixels, that grabs pixels in any orientation including standing up and from the stacks. An over-center linkage holds the intake lifted for transfer with no power. The "bowtie" shape at the back of the intake is what positions pixels for a clean handoff; rotating the tubing sets 90° to each other was the biggest throughput gain. Compliant-wheel and side-sweeper versions were discarded for jamming and for failing to seat two pixels side by side.' },
        { heading: 'Elevator, tilt and gantry', text: 'Two parallel 3-stage 300 mm Misumi slides, belted, with the idler assembly on the driving-pulley shaft (V1 put idlers too far from the motor). The whole extension rests on an 8 mm shaft carried by lead screws on each side — the tilt — so it can reach any backdrop height and score from a distance, which speeds up autonomous. A rack-and-pinion gantry on a 5-turn SuperSpeed servo fine-positions the scorer between transfer and scoring.' },
        { heading: 'Scorer', text: 'Two micro-servo clamps in a printed frame hold two pixels and release them independently; ball switches in the base plate detect the backdrop and trigger auto-release, and the scorer hangs on surgical tubing so it complies when the robot is not parallel to the board. A TPU "pixel mover" on the gantry grabs the inside of a pixel to nudge mosaics. Side-pinch V1 was too bulky and the divider between pixels kept snapping.' },
        { heading: 'Endgame', bullets: [
          'Drone launcher: clamp-and-release carriage on an MGN9 linear rail, mounted on the hang mechanism for extra height; 56° total launch angle chosen after 10+ landings per version at 71°, 66°, and 56°.',
          'Hang: geared lead screws on 3.7:1 motors, both sides, hubs on 1 in bearings; Delrin hooks flip over the bar and the screws pull the robot up.',
        ]},
        { heading: 'Software', text: 'State machine (INTAKE → TRANSFER → SWING → EXTEND → SCORE → RETRACT) driven by sensors: HuskyLens for pixel stacks, webcam AprilTags for backdrop column alignment and localization cross-check, ultrasonic for stack distance, REV color sensor to auto-advance from intake to transfer. Custom Pure Pursuit with a per-segment lookahead radius, a DualPad class that merges both gamepads and adds shift keys, haptics on two pixels, and an LED preset display.' },
      ],
      images: [
        { src: 'assets/img/athena/00-athena-cutout.jpg', fit: 'contain', alt: 'Athena full robot', caption: 'Athena — tilting belted elevator, gantry, and two-pixel scorer' },
        { src: 'assets/img/athena/02-elevator-gantry-cad.jpg', fit: 'contain', alt: 'Elevator slides and gantry CAD', caption: 'Belted Misumi elevator with rack-and-pinion gantry' },
        { src: 'assets/img/athena/03-intake-tilt-cad.jpg', fit: 'contain', alt: 'Intake and tilt arm CAD', caption: 'Surgical-tubing intake on over-center lift' },
        { src: 'assets/img/athena/04-drivetrain-cad.jpg', fit: 'contain', alt: 'Drivetrain chassis CAD', caption: 'Compact direct-drive mecanum chassis' },
        { src: 'assets/img/athena/05-team-trophies.jpg', alt: 'Team with trophies and robot', caption: 'FiT-North Area Championship' },
        { src: 'assets/img/athena/06-build-session.jpg', alt: 'Two members working on the robot', caption: 'Build session' },
      ],
      links: [
        { label: 'Behind the Bot — Centerstage (FUN)', href: 'https://youtu.be/VW5LuiKfoOg' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2023' },
      ],
    },
    {
      id: 'rebound',
      cardImage: 1,
      title: '"Rebound" — Spindexer Shooter Robot, FTC Decode',
      date: '2025 – 2026',
      role: 'Lead designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Flywheel', 'Telescoping hood', 'Turret', 'Spindexer', 'Compliant wheels', 'Servo profiling'],
      summary: 'Three balls sorted and shot in 0.2–0.5 s from anywhere on the field: a full-width compliant intake, a wedge spindexer that sorts without stopping, a sprung-cam hammer feed, and a flywheel with a coaxial telescoping hood on a 200 Hz servo turret. World Championship Finalist Alliance.',
      facts: [
        { label: 'Result', value: 'Worlds Goodall Division Winner → FIRST Championship Finalist Alliance (4–3 in finals)' },
        { label: 'Regional', value: 'FiT-North Regional Division Finalist' },
        { label: 'Shot cycle', value: '3 balls in 0.2–0.5 s, distance-based lookup' },
        { label: 'Spindexer', value: '3 balls in < 0.5 s at 120 rpm, 19.2:1' },
        { label: 'Turret', value: '200 Hz PID after 5 ms PWM frame' },
      ],
      sections: [
        { heading: 'Intake', text: 'Wide as the robot, with compliant Swyft wheels on a pivot so they keep full grip while balls compress, wedges to pull from corners and walls, and a front plate shaped to hit the gate. Vectored wheels in V1 barely vectored and broke easily. Moving the intake up 8 mm stopped balls being driven down instead of back; larger wheels gave a smoother handoff into the spindexer. Reversing the wheels ejects a fourth ball.' },
        { heading: 'Spindexer', text: 'A wedge-shaped agitator that takes balls at intake speed and sorts them while spinning, instead of a three-pronged indexer that had to stop to load. The opening is exactly two artifacts wide, the spindexer is tangent to the intake with top and bottom guides, and a servo ramp redirects balls in. Lessons: minimize ball-to-guide contact area, add grip tape where balls spin unpredictably, and constrain the balls at every point so it can run fast. Symmetric so it unjams from either side and can spit out an extra ball without releasing the others.' },
        { heading: 'Hammer', text: 'A sprung-cam compliant wheel that engages the ball at its equator and pushes it all the way into the flywheel, so selection is precise and nothing jams between spindexer and shooter. The passive ramp did not engage fast enough, so it became an active servo ramp; the tubing anchor had to move because it lacked torque. The whole hammer unbolts as a unit.' },
        { heading: 'Shooter', text: 'Flywheel with added inertia, geared 3:2 for a 4000 rpm target, under closed-loop velocity control so near and far shots land the same; artifacts are withheld until the wheel is at speed. The angled hood had too much play and a big footprint, so it became a continuous telescoping hood on a coaxial gear — a consistent low arc into the backboard from any position rather than lobbing into the goal. One motor was left for the shooter after the rest of the robot, so windup speed was chosen over raw wheel speed.' },
        { heading: 'Controls', bullets: [
          'Distance to goal (odometry + AprilTags) indexes a lookup table for hood angle, flywheel velocity, and spindexer speed, linearly interpolated between tuned points.',
          'Dual color-sensor array sequences artifacts by elimination to hit the sorting ranking point.',
          'Pub/sub architecture so every subscriber of a topic runs when it changes.',
          'Servo profiling: characterized the turret servo (about 20,000 ticks/s max, 40 ms command-to-motion lag, slower decel than accel) and cut the PWM frame from the SDK default 20 ms to 5 ms — lag down 4× to 10 ms, PID loop at 200 Hz.',
          'Sensors: 4-bar odometry pods, REV bore encoder on the turret, Swyft Ranger distance sensor to refuse a fourth ball, limit switch to re-zero the spindexer.',
        ]},
      ],
      images: [
        { src: 'assets/img/rebound/01-robot-cad.jpg', fit: 'contain', alt: 'Rebound full robot CAD', caption: 'Rebound — turret shooter, spindexer, full-width intake' },
        { src: 'assets/img/rebound/02-competition-photo.jpg', alt: 'Rebound launching an artifact at a Decode competition', caption: 'Rebound mid-shot at competition' },
        { src: 'assets/img/rebound/02-turret-shooter-cad.jpg', fit: 'contain', alt: 'Turret shooter with flywheel and telescoping hood', caption: 'Flywheel shooter with coaxial telescoping hood' },
        { src: 'assets/img/rebound/03-spindexer-loaded-cad.jpg', alt: 'Chassis top view with artifacts in the spindexer', caption: 'Spindexer loaded — opening is exactly two artifacts wide' },
        { src: 'assets/img/rebound/04-intake-cad.jpg', fit: 'contain', alt: 'Intake roller with compliant fingers', caption: 'Full-width compliant intake' },
        { src: 'assets/img/rebound/05-spindexer-ring-cad.jpg', fit: 'contain', alt: 'Spindexer ring with servo and gear', caption: 'Spindexer ring and drive' },
        { src: 'assets/img/rebound/06-hammer-spindexer-cad.jpg', fit: 'contain', alt: 'Hammer and spindexer assembly', caption: 'Sprung-cam hammer over the spindexer' },
        { src: 'assets/img/rebound/07-arm-cad.jpg', fit: 'contain', alt: 'Arm tri-plate on motor shaft', caption: 'Arm plates' },
        { src: 'assets/img/rebound/08-hood-side-cad.jpg', fit: 'contain', alt: 'Shooter hood side view', caption: 'Hood enclosure, side' },
        { src: 'assets/img/rebound/10-robot-rear-cad.jpg', fit: 'contain', alt: 'Rebound from the rear', caption: 'Rebound — rear three-quarter' },
        { src: 'assets/img/rebound/11-intake-bar-cad.jpg', fit: 'contain', alt: 'Full-width intake bar', caption: 'Intake bar — compliant wheels across the full width' },
        { src: 'assets/img/rebound/09-team-first-in-texas.jpg', alt: 'Team with Rebound at FIRST in Texas', caption: 'Team 7172 with Rebound' },
      ],
      links: [
        { label: 'FIRST blog — Championship Finalist Alliance', href: 'https://community.firstinspires.org/congratulations-to-our-decode-first-championship-teams' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2025' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/rebound' },
      ],
    },
    {
      id: 'drone-launcher',
      cardImage: 3,
      title: 'Paper-Airplane "Drone" Launcher — FTC Centerstage',
      date: '2023 – 2024',
      role: 'Designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Constant-force', 'Linear rail', 'Aerodynamics', 'Rapid prototyping'],
      summary: 'A surgical-tubing launcher that snapped at the State Championship became a tension-free constant-force design that hit Zone 1 in 8 of 10 matches at the Maryland Tech Invitational.',
      facts: [
        { label: 'Versions', value: '3 launcher + dozens of plane folds' },
        { label: 'Accuracy', value: 'Zone 1 in 8/10 matches (MTI)' },
        { label: 'Award', value: 'Hardware Mastery · Finalist Alliance 1st pick' },
      ],
      sections: [
        { heading: 'Problem', text: 'Centerstage scored a paper airplane launched over the field wall into one of three zones. V1 used stretched surgical tubing to accelerate a carriage on a linear rail. It was consistent in testing, but consistency degraded as the tubing tension drifted — and while re-tensioning at the State Championship, the mechanism snapped in half.' },
        { heading: 'Design', bullets: [
          'Redesigned after States around a mechanism that needs no re-tensioning (inspired by team 17315 Tomahawk). First prototype was built at home while out with Covid.',
          'Planes needed slightly negative static stability so they stall and settle into the zone rather than glide past it; ±0.5 mm fold variance was enough to change the landing, so each plane was hand-tuned over hundreds of launches.',
          'Ran structured testing: launch, mark landing, compare accuracy and precision across fold patterns and launcher versions.',
        ]},
        { heading: 'Outcome', text: 'At the Maryland Tech Invitational (40-team invitational at JHU APL) the launcher scored Zone 1 in 8 of 10 matches, Zone 2 once, and missed once on a timing error — contributing to Finalist Alliance 1st Pick and the Hardware Mastery Award.' },
      ],
      images: [
        { src: 'assets/img/launcher/01-final-cad.jpg', fit: 'contain', alt: 'Final launcher CAD render', caption: 'Final design — no re-tensioning required' },
        { src: 'assets/img/launcher/02-v1-surgical-tubing-cad.jpg', alt: 'V1 launcher CAD with surgical tubing', caption: 'V1 — surgical tubing on a linear rail' },
        { src: 'assets/img/launcher/03-rail-cad.jpg', alt: 'Launcher carriage on rail CAD', caption: 'Carriage + rail iteration' },
        { src: 'assets/img/launcher/04-prototype-a.jpg', alt: 'Hand-held blue prototype', caption: 'First printed prototype' },
        { src: 'assets/img/launcher/05-prototype-b.jpg', alt: 'Prototype rear view', caption: 'Prototype, rear' },
        { src: 'assets/img/launcher/06-landing-zones.jpg', alt: 'Landing zone scatter diagram', caption: 'Landing-zone test results' },
      ],
      links: [
        { label: 'V1 testing video', href: 'https://www.youtube.com/watch?v=RNoj_P2VNBY' },
        { label: 'V2 initial testing', href: 'https://drive.google.com/file/d/1WoOeyi_kb7Gg0BDK5wNNIA0lv1Q3RA16/view' },
      ],
    },
    {
      id: 'pickleball-robot',
      title: 'Pickleball Ball-Boy Robot',
      date: 'May 2025 – present',
      role: 'Solo project',
      featured: true,
      categories: ['Robotics', 'Software'],
      tags: ['Jetson Orin Nano', 'Arduino', 'OpenCV', 'AprilTag', 'RealSense D435', 'T265', 'Euler integration'],
      summary: 'Ground-vehicle testbed for a UAV that catches practice serves: RGB-D ball detection, AprilTag localization, and a drag-corrected trajectory predictor that lands the intercept inside a 20 cm target zone.',
      facts: [
        { label: 'Compute', value: 'Jetson Orin Nano → Arduino Nano (serial)' },
        { label: 'Localization', value: 'AprilTag @ ~20 fps (best of 4 methods)' },
        { label: 'Free speed', value: '~8.6 m/s theoretical' },
      ],
      sections: [
        { heading: 'Why', text: 'I like pickleball and am bad at it. Practice needs a partner, so the plan is a UAV that takes off from the court and catches practice serves. The holonomic drive base is a cheap testbed for the full perception-and-intercept stack before buying an expensive airframe.' },
        { heading: 'Perception', bullets: [
          'Benchmarked ball detection methods: HSV filtering, RGB contour detection, circularity filtering, depth-discontinuity detection, and YOLO. Production path: HSV mask → most-circular contour → "depth pixel" sampled from the RealSense depth map, with far/invalid depths rejected.',
          'Benchmarked localization: global-shutter VSLAM, T265 VSLAM, optical flow, and AprilTag. AprilTag on a global-shutter camera was the most accurate by a wide margin.',
        ]},
        { heading: 'Trajectory prediction', text: 'From 5+ observed points, solve initial position and velocity (recent points weighted higher), then run a 50-step Euler integration with drag and gravity to find where the ball meets the ground plane. A single drag coefficient failed because of Magnus effect; separate horizontal and vertical coefficients (vertical much higher) matched real flights, with the true landing point inside a 20 cm radius target zone.' },
        { heading: 'Control', text: 'A P controller on the Jetson sends heading and power to the Arduino, which converts them to PWM for four motor controllers. Current code assumes a fixed heading — heading control is next.' },
      ],
      images: [
        { src: 'assets/img/pickleball/01-chassis-electronics.jpg', alt: 'Chassis with Jetson, T265, global shutter camera, Arduino', caption: 'Testbed electronics — Jetson Orin Nano, T265, global-shutter cam, Arduino Nano' },
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/Randomfalcon124/PickleBallDrone-main' },
        { label: 'Ball detection demo', href: 'https://drive.google.com/file/d/1HRkXoVJWfmUpVvsF8ZYCf25goq4tGFhf/view' },
        { label: 'Trajectory prediction demo', href: 'https://drive.google.com/file/d/1ghIXcx0HapQh7FFHHHO9YrD25-o6ufu3/view' },
        { label: 'Robot control demo', href: 'https://drive.google.com/file/d/11jU2Om0csPG5VMqSasA9x8ZPP-slJiSK/view' },
      ],
    },
    {
      id: 'bwsi-sar',
      title: 'UAV Synthetic Aperture Radar — MIT BWSI',
      date: 'Summer 2024',
      role: 'Student, UAS-SAR track',
      categories: ['Aerospace', 'Software'],
      tags: ['Python', 'NumPy', 'Matplotlib', 'Pandas', 'PulsON 440', 'DJI F550', 'Signal processing'],
      summary: 'Mounted a PulsON 440 radar on a DJI F550 and wrote a vectorized back-projection algorithm to image obscured objects from radar scans along the flight path.',
      facts: [
        { label: 'Program', value: 'MIT Beaver Works Summer Institute' },
        { label: 'Radar', value: 'PulsON 440 UWB' },
        { label: 'Positioning', value: 'IR motion capture' },
      ],
      sections: [
        { heading: 'Concept', text: 'A UAV flying past a scene collects radar returns from many positions, synthesizing a much larger aperture than the physical antenna. Noise adds destructively across scans, so the combined image is cleaner than any single one.' },
        { heading: 'Pipeline', bullets: [
          'Range-Time-Intensity (RTI) plots to calibrate the radar before anything fancier; an RTI-delta plot (difference between consecutive scans) highlights moving targets.',
          'Back-projection: choose the image area and resolution, then for every pixel and every scan, find the distance from the UAV (from mocap) to that pixel and accumulate the return intensity at that range. Written with NumPy vectorized ops to keep it fast.',
          'Pandas to ingest and filter the IR motion-capture stream; Matplotlib for all plots and image display.',
        ]},
        { heading: 'Result', text: 'Resolved all four soda cans in the test scene despite two extremely bright retroreflectors next to them. The drone code led the cohort; the radar code lagged and got debugged the night before the flight test.' },
      ],
      images: [
        { src: 'assets/img/sar/01-rti-plot.jpg', fit: 'contain', alt: 'Range-time-intensity plot', caption: 'Range-Time-Intensity plot' },
        { src: 'assets/img/sar/05-backprojection.jpg', alt: 'Back-projection SAR image of reflectors', caption: 'Back-projected image — dots mark true reflector positions' },
        { src: 'assets/img/sar/02-rti-delta.jpg', alt: 'RTI delta plot', caption: 'RTI delta — moving objects pop out' },
        { src: 'assets/img/sar/03-rti-annotated.jpg', alt: 'Annotated RTI plot', caption: 'Annotated RTI' },
        { src: 'assets/img/sar/04-simulated-points.jpg', alt: 'Simulated five-point target', caption: 'Simulated five-point target for validating back-projection' },
        { src: 'assets/img/sar/06-flight-test.jpg', alt: 'Netted indoor flight test area', caption: 'Indoor flight test range' },
      ],
      links: [
        { label: 'Flight demo', href: 'https://docs.google.com/videos/d/1nTDq4MYMFNl97QRyq96pn62LJCfdCmdN-ImJtG1f_Ok/edit' },
      ],
    },
    {
      id: 'master-sketches',
      title: 'Master-Sketch-Driven CAD',
      date: '2022 – 2026',
      role: 'CAD workflow',
      categories: ['CAD'],
      tags: ['Fusion 360', 'Parametric', 'Top-down design', 'Onshape'],
      summary: 'Evolving from one crowded master sketch that only I could edit to layered sketches that let teammates change a mechanism by editing a handful of dimensions.',
      sections: [
        { heading: 'V1 — one sketch to rule them all', text: 'For the first Valkyrie scoring extension, a single master sketch controlled most features in the mechanism: change one dimension or constraint and the whole model followed. It worked — but it got so crowded it became hard for me and impossible for anyone else.' },
        { heading: 'V2 — layered sketches', text: 'For the next version I split control across four sketches: one for the basic dimensions and position, and one each for the inner/outer side plates and the belt-and-pulley idlers. Much cleaner, and teammates could actually work with the model.' },
        { heading: 'Now', text: 'The master sketch for our Decode-season ball shooter and transfer is deliberately simple — the lesson is that the sketch exists to be read by other people, not to be clever.' },
      ],
      images: [
        { src: 'assets/img/sketches/01-shooter-cad.jpg', fit: 'contain', alt: 'Ball shooter turret CAD render', caption: 'Decode ball shooter — driven by the sketch below' },
        { src: 'assets/img/sketches/02-valkyrie-v1-sketch.jpg', alt: 'Crowded V1 master sketch', caption: 'V1 master sketch — fully constrained, unreadable' },
        { src: 'assets/img/sketches/03-layered-sketch.jpg', alt: 'Layered scoring extension sketch', caption: 'V2 — four layered sketches' },
        { src: 'assets/img/sketches/04-shooter-sketch.jpg', alt: 'Ball shooter geometry sketch', caption: 'Shooter wheel geometry sketch' },
        { src: 'assets/img/sketches/05-arm-profile-sketch.jpg', alt: 'Arm profile sketch', caption: 'Arm profile sketch' },
      ],
    },
    {
      id: 'rocketry',
      title: 'Fully 3D-Printed Model Rockets',
      date: '2023 – 2026',
      role: 'Rocketry Club founder & president',
      categories: ['Aerospace', 'CAD'],
      tags: ['Onshape', 'OpenRocket', '3D printing', 'Afinia H+1', 'Stability'],
      summary: 'Founded the club to build and fly rockets from whatever we had — mostly an Afinia H+1 printer. Air, water, and solid-fuel rockets; some came down too fast, one never came down.',
      sections: [
        { heading: 'Design', bullets: [
          'Printed airframes and fins modeled in Onshape, flight-simulated in OpenRocket.',
          'Adjustable nose-weight compartment on a rotational dovetail slider to tune static stability without reprinting.',
        ]},
        { heading: 'Failures', text: 'Parachute failures (came down too fast), launch failures, and one rocket that went into the clouds and was never seen again. Each one fed the next print.' },
      ],
      images: [
        { src: 'assets/img/rocketry/01-printed-sections.jpg', alt: 'Printed rocket sections laid out', caption: 'Printed airframe sections' },
        { src: 'assets/img/rocketry/02-assembled.jpg', alt: 'Assembled rocket standing upright', caption: 'Assembled' },
        { src: 'assets/img/rocketry/03-onshape.jpg', alt: 'Onshape rocket assembly', caption: 'Onshape assembly' },
        { src: 'assets/img/rocketry/04-openrocket.jpg', alt: 'OpenRocket simulation', caption: 'OpenRocket flight simulation' },
      ],
      links: [
        { label: 'Launch videos', href: 'https://drive.google.com/drive/folders/111P74FA-54lxr2Gh_t-UcjrSUF1K22-_' },
      ],
    },
    {
      id: 'telescope',
      cardImage: 2,
      title: '3D-Printed Telescope',
      date: '2025',
      role: 'With David (Physics 2)',
      categories: ['CAD'],
      tags: ['Fusion 360', 'Optics', 'Carbon fiber rods', '3D printing'],
      summary: 'Assigned a ray diagram of a telescope, we built one instead — printed lens clamps on carbon-fiber rods, and a crash course in why identical lenses don\'t compound.',
      sections: [
        { heading: 'Design', bullets: [
          'Carbon-fiber rods for stiffness; printed ring clamps slide along them so lens spacing is adjustable.',
          'Clamp slit sized for different lens types (concave, convex); loosen screws to reposition.',
        ]},
        { heading: 'What we learned', text: 'We expected stacking lenses to compound magnification. It doesn\'t — magnification comes from the focal-length difference between objective and eyepiece, and ours were identical. Fix: stack several lenses close together to emulate a shorter focal length, then place one further away. The final image was blurry (chromatic aberration) and inverted (no erecting lens), and it briefly worked better as a microscope. Presented at the Spark STEM outreach program.' },
      ],
      images: [
        { src: 'assets/img/telescope/01-truss-cad.jpg', alt: 'Full telescope truss CAD', caption: 'Ring-truss assembly CAD' },
        { src: 'assets/img/telescope/02-clamp-cad.jpg', alt: 'Lens clamp bracket CAD', caption: 'Lens clamp' },
        { src: 'assets/img/telescope/03-truss-photo.jpg', alt: 'Carbon rod truss with printed rings', caption: 'Printed rings on carbon rods' },
        { src: 'assets/img/telescope/04-assembly.jpg', alt: 'Assembling the telescope in class', caption: 'Assembly' },
      ],
    },
    {
      id: 'window-counter',
      title: 'Autonomous House-Mapping Robot',
      date: '2025 – present',
      role: 'Solo project',
      categories: ['Robotics', 'Software'],
      tags: ['ROS 2', 'Nav2', 'RTAB-Map', 'Jetson', 'Frontier exploration', 'VSLAM', 'systemd'],
      summary: 'A Jetson-based robot that explores a house on its own, builds a persistent map, and counts windows — frontier-based exploration on the ROS 2 Nav2 stack with RTAB-Map visual SLAM.',
      sections: [
        { heading: 'Stack', bullets: [
          'ROS 2 Nav2 for path planning; custom frontier explorer picks goals; RTAB-Map VSLAM keeps maps persistent across sessions.',
          'A per-tick safety governor and an arm/disarm daemon — no motion without an explicit arm file, self-disarm on any safety trip.',
          'Auto-start and self-heal: a systemd service plus a health-gated watchdog timer bring the stack back after power cuts or DDS discovery races.',
          'Vision-language model handles window recognition from captured frames.',
        ]},
        { heading: 'Status', text: 'Operational; autonomy stack still being hardened.' },
      ],
      images: [],
    },
    {
      id: 'fusion-scripts',
      title: 'Fusion 360 Automation Scripts',
      date: '2023 – present',
      role: 'Solo project',
      categories: ['CAD', 'Software'],
      tags: ['Fusion 360 API', 'Python', 'Parametric', 'Workflow'],
      summary: 'Scripts that generate REV Robotics extrusion at any length, auto-model screws with threads and chamfers, and (almost) duplicate components to selected locations.',
      sections: [
        { heading: 'Details', bullets: [
          'REV extrusion generator: the most common structural part on my FTC team, now one prompt instead of a modeling session.',
          'Screw generator written to learn automating threads and chamfers through the API.',
          'Component-duplicate-to-locations script — a feature Onshape had and Fusion lacked. Fusion shipped it natively before I finished, so I stopped.',
        ]},
      ],
      images: [],
      links: [
        { label: 'Extrusion script demo', href: 'https://drive.google.com/file/d/18fCxM1h6V8WSYh84AdAiBbvuGsqVMpSP/view' },
      ],
    },
  ],

  /* ---------------- CAD GALLERY ----------------
     Either reference a project image ({project, index}) or give a standalone {src, caption, tool}. */
  gallery: [
    { project: 'dual-arm-robot', index: 0, tool: 'Fusion 360' },
    { project: 'rebound', index: 0, tool: 'Fusion 360' },
    { project: 'defiant', index: 0, tool: 'Fusion 360' },
    { project: 'nautilus', index: 0, tool: 'Fusion 360' },
    { project: 'dual-arm-robot', index: 7, tool: 'Fusion 360' },
    { project: 'rebound', index: 3, tool: 'Fusion 360' },
    { project: 'athena', index: 1, tool: 'Fusion 360' },
    { project: 'defiant', index: 4, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 0, tool: 'Fusion 360' },
    { project: 'rebound', index: 6, tool: 'Fusion 360' },
    { project: 'defiant', index: 6, tool: 'Fusion 360' },
    { project: 'nautilus', index: 2, tool: 'Fusion 360' },
    { project: 'dual-arm-robot', index: 15, tool: 'Fusion 360' },
    { project: 'rebound', index: 5, tool: 'Fusion 360' },
    { project: 'telescope', index: 0, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 1, tool: 'Fusion 360 sketch' },
    { project: 'rocketry', index: 2, tool: 'Onshape' },
    { project: 'defiant', index: 3, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 2, tool: 'Fusion 360 sketch' },
    { project: 'nautilus', index: 3, tool: 'Fusion 360' },
    { project: 'dual-arm-robot', index: 16, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 3, tool: 'Fusion 360 sketch' },
  ],

  /* ---------------- EXPERIENCE ---------------- */
  experience: [
    { role: 'Hypersonics Student Researcher', org: 'Georgia Tech VIP Program', date: 'Aug 2026 – present', bullets: ['Vertically Integrated Projects research team, Atlanta, GA.'] },
    { role: 'Co-Founder', org: 'Hardpoint Robotics', date: 'May 2026 – present', bullets: ['Designing and building NDAA-compliant development UAVs; FAA Part 107 certified.', 'Airframe CAD, CF-Nylon printed parts, vendor-manufactured carbon-fiber structure.'] },
    { role: 'Engineering Design Intern', org: 'SWYFT Robotics', date: 'May 2025 – May 2026', bullets: ['Sprockets, gears, pulleys, and a modular robot cart for FIRST teams.', 'Low-cost manufacturing via extrusion and fiber-laser cutting.'] },
    { role: 'Captain & Lead Designer', org: 'FTC Team 7172 Technical Difficulties', url: 'https://ftc7172.org', date: 'Sep 2021 – May 2026', bullets: ['Finalist Alliance at the 2026 FIRST Championship; four World Championship appearances; #1 np-OPR worldwide in 2021–22.', '245–73–2 in qualification matches over five seasons, 19 event wins, 63 awards including Inspire, Think, Connect, Innovate, Design, and Control awards.', 'Mechanisms: linkages, counter-springing, pulley systems, geartrains, 6-DOF arms.', 'Reviewed 85 applications, ran 40 interviews, and onboarded 13 new members; set up the team\'s 501(c)(3).'] },
    { role: 'Student, UAS-SAR', org: 'MIT Beaver Works Summer Institute', date: 'Jun – Aug 2024', bullets: ['Synthetic aperture radar imaging from a DJI F550 with a PulsON 440 radar.'] },
    { role: 'Founder & President', org: 'Rocketry Club', date: 'Mar 2023 – May 2026', bullets: ['Designed, printed, flew, and frequently crashed model rockets.'] },
    { role: 'Co-Captain', org: 'Academic Decathlon', date: 'Sep 2023 – May 2026', bullets: ['2nd at State; gold in mathematics.'] },
    { role: 'B.S. Aerospace Engineering', org: 'Georgia Institute of Technology', date: '2026 – 2029', bullets: [] },
    { role: 'High School Diploma', org: 'School of Science and Engineering, Dallas TX', date: '2022 – 2026', bullets: ['3.97 UW GPA · Rank 2 · 1600 SAT · National Merit Scholar · NASA High School Aerospace Scholar.'] },
  ],

  /* ---------------- SKILLS ---------------- */
  skills: [
    { group: 'CAD & Manufacturing', items: ['Fusion 360', 'Onshape', 'SolidWorks', 'Autodesk Inventor (certified)', 'FEA', 'Master sketches', '3D printing', 'CF-Nylon', 'Laser cutting', 'CNC', 'DFM'] },
    { group: 'Robotics & Embedded', items: ['NVIDIA Jetson', 'ROS 2 / Nav2', 'RTAB-Map', 'ArduPilot', 'Arduino', 'Raspberry Pi', 'REV Control Hub', 'OpenCV', 'AprilTag', 'RealSense / T265'] },
    { group: 'Programming', items: ['Python', 'NumPy', 'Pandas', 'Matplotlib', 'TensorFlow', 'JavaScript', 'HTML/CSS', 'SQL', 'Git'] },
    { group: 'Aerospace', items: ['UAV airframe design', 'FAA Part 107', 'OpenRocket', 'Synthetic aperture radar', 'Trajectory modeling'] },
  ],
};
