/* ============================================================
   PORTFOLIO CONTENT — edit this file to update the site.
   Images live in assets/img/<project>/. First image = card thumbnail.
   ============================================================ */
window.PORTFOLIO = {
  profile: {
    name: 'Akshay Patil',
    siteTitle: 'Engineering Portfolio',
    eyebrow: 'Aerospace Engineering · Georgia Tech',
    tagline: 'Mechanical design, robotics, and UAVs — the projects behind the resume.',
    blurb: 'I design and build things that move: competition robots, UAV airframes, launchers, rockets, and the CAD workflows that make iterating on them fast. This site is the long-form companion to my resume — the failures, redesigns, and numbers that don\'t fit on one page.',
    resume: 'assets/AkshayPatil_Resume.pdf',
    cta: [
      { label: 'View projects', href: '#projects' },
      { label: 'Resume (PDF)', href: 'assets/AkshayPatil_Resume.pdf', external: true },
      { label: 'Portfolio PDF', href: 'assets/AkshayPatil_Portfolio_compact.pdf', external: true },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/akshaypatil08', external: true },
    ],
    stats: [
      { value: 'Finalist', label: '2026 FIRST Championship alliance' },
      { value: '5 robots', label: 'FTC competition robots — lead designer on 4' },
      { value: '6 yrs', label: 'Fusion 360 / Onshape / SolidWorks' },
      { value: 'Part 107', label: 'FAA remote pilot' },
    ],
    contactBlurb: 'Open to internships and research in mechanical design, robotics, and UAS. Fastest way to reach me is email.',
    links: [
      { label: 'akshaypat08@gmail.com', href: 'mailto:akshaypat08@gmail.com' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/akshaypatil08' },
      { label: 'GitHub', href: 'https://github.com/Randomfalcon124' },
      { label: 'FTC 7172', href: 'https://ftc7172.org' },
    ],
  },

  /* ---------------- PROJECTS ---------------- */
  projects: [
    {
      id: 'rebound',
      cardImage: 1,
      title: '"Rebound" — Spindexer Shooter Robot, FTC Decode',
      date: '2025 – 2026',
      role: 'Lead designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Flywheel', 'Telescoping hood', 'Turret', 'Spindexer', 'Compliant wheels', 'Servo profiling'],
      summary: 'Three balls sorted and shot in 0.2–0.5 s from anywhere on the field: a full-width compliant intake, a wedge spindexer that sorts without stopping, a sprung-cam hammer feed, and a flywheel with a coaxial telescoping hood on a 200 Hz servo turret. World Championship Finalist Alliance.',
      facts: [
        { label: 'Result', value: 'Worlds Goodall Division Winner → FIRST Championship Finalist Alliance (4–3 in finals)' },
        { label: 'Regional', value: 'FiT-North Regional Division Finalist' },
        { label: 'Shot cycle', value: '3 balls in 0.2–0.5 s, distance-based lookup' },
        { label: 'Spindexer', value: '3 balls in < 0.5 s at 120 rpm, 19.2:1' },
        { label: 'Turret', value: '200 Hz PID after 5 ms PWM frame' },
      ],
      sections: [
        { heading: 'Intake', text: 'Wide as the robot, with compliant Swyft wheels on a pivot so they keep full grip while balls compress, wedges to pull from corners and walls, and a front plate shaped to hit the gate. Vectored wheels in V1 barely vectored and broke easily. Moving the intake up 8 mm stopped balls being driven down instead of back; larger wheels gave a smoother handoff into the spindexer. Reversing the wheels ejects a fourth ball.' },
        { heading: 'Spindexer', text: 'A wedge-shaped agitator that takes balls at intake speed and sorts them while spinning, instead of a three-pronged indexer that had to stop to load. The opening is exactly two artifacts wide, the spindexer is tangent to the intake with top and bottom guides, and a servo ramp redirects balls in. Lessons: minimize ball-to-guide contact area, add grip tape where balls spin unpredictably, and constrain the balls at every point so it can run fast. Symmetric so it unjams from either side and can spit out an extra ball without releasing the others.' },
        { heading: 'Hammer', text: 'A sprung-cam compliant wheel that engages the ball at its equator and pushes it all the way into the flywheel, so selection is precise and nothing jams between spindexer and shooter. The passive ramp did not engage fast enough, so it became an active servo ramp; the tubing anchor had to move because it lacked torque. The whole hammer unbolts as a unit.' },
        { heading: 'Shooter', text: 'Flywheel with added inertia, geared 3:2 for a 4000 rpm target, under closed-loop velocity control so near and far shots land the same; artifacts are withheld until the wheel is at speed. The angled hood had too much play and a big footprint, so it became a continuous telescoping hood on a coaxial gear — a consistent low arc into the backboard from any position rather than lobbing into the goal. One motor was left for the shooter after the rest of the robot, so windup speed was chosen over raw wheel speed.' },
        { heading: 'Controls', bullets: [
          'Distance to goal (odometry + AprilTags) indexes a lookup table for hood angle, flywheel velocity, and spindexer speed, linearly interpolated between tuned points.',
          'Dual color-sensor array sequences artifacts by elimination to hit the sorting ranking point.',
          'Pub/sub architecture so every subscriber of a topic runs when it changes.',
          'Servo profiling: characterized the turret servo (about 20,000 ticks/s max, 40 ms command-to-motion lag, slower decel than accel) and cut the PWM frame from the SDK default 20 ms to 5 ms — lag down 4× to 10 ms, PID loop at 200 Hz.',
          'Sensors: 4-bar odometry pods, REV bore encoder on the turret, Swyft Ranger distance sensor to refuse a fourth ball, limit switch to re-zero the spindexer.',
        ]},
      ],
      images: [
        { src: 'assets/img/rebound/01-robot-cad.jpg', fit: 'contain', alt: 'Rebound full robot CAD', caption: 'Rebound — turret shooter, spindexer, full-width intake' },
        { src: 'assets/img/rebound/02-competition-photo.jpg', alt: 'Rebound launching an artifact at a Decode competition', caption: 'Rebound mid-shot at competition' },
        { src: 'assets/img/rebound/02-turret-shooter-cad.jpg', fit: 'contain', alt: 'Turret shooter with flywheel and telescoping hood', caption: 'Flywheel shooter with coaxial telescoping hood' },
        { src: 'assets/img/rebound/03-spindexer-loaded-cad.jpg', alt: 'Chassis top view with artifacts in the spindexer', caption: 'Spindexer loaded — opening is exactly two artifacts wide' },
        { src: 'assets/img/rebound/04-intake-cad.jpg', fit: 'contain', alt: 'Intake roller with compliant fingers', caption: 'Full-width compliant intake' },
        { src: 'assets/img/rebound/05-spindexer-ring-cad.jpg', fit: 'contain', alt: 'Spindexer ring with servo and gear', caption: 'Spindexer ring and drive' },
        { src: 'assets/img/rebound/07-arm-cad.jpg', fit: 'contain', alt: 'Arm tri-plate on motor shaft', caption: 'Arm plates' },
        { src: 'assets/img/rebound/08-hood-side-cad.jpg', fit: 'contain', alt: 'Shooter hood side view', caption: 'Hood enclosure, side' },
        { src: 'assets/img/rebound/10-robot-rear-cad.jpg', fit: 'contain', alt: 'Rebound from the rear', caption: 'Rebound — rear three-quarter' },
        { src: 'assets/img/rebound/11-intake-bar-cad.jpg', fit: 'contain', alt: 'Full-width intake bar', caption: 'Intake bar — compliant wheels across the full width' },
        { src: 'assets/img/rebound/09-team-first-in-texas.jpg', alt: 'Team with Rebound at FIRST in Texas', caption: 'Team 7172 with Rebound' },
      ],
      links: [
        { label: 'FIRST blog — Championship Finalist Alliance', href: 'https://community.firstinspires.org/congratulations-to-our-decode-first-championship-teams' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2025' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/rebound' },
      ],
    },
    {
      id: 'dual-arm-robot',
      title: '"Phoenix" — Dual-Arm Turret Robot, FTC Power Play',
      date: '2022 – 2023',
      role: 'Lead designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Worm gearboxes', 'Rack & pinion', 'Turret', 'Inverse kinematics', 'Double-helical gears', 'Misumi slides', 'HuskyLens'],
      summary: 'Two three-pivot arms on worm-gear turrets, riding a drivetrain that splits in half on linear slides: 13 ft of reach, no transfer, ~4 s cycles, and all ten cones in autonomous. Worlds division finalist and Innovate Award winner.',
      facts: [
        { label: 'Team', value: 'FTC 7172 Technical Difficulties' },
        { label: 'Result', value: 'Worlds Ochoa Division Finalist · Innovate Award (RTX)' },
        { label: 'Reach', value: '13 ft — 5 ft drivetrain split + two 4 ft arms' },
        { label: 'Season', value: 'TX State Finalist · TX-North Regional champion (6–0) · np-OPR #10 of 5,671' },
      ],
      sections: [
        { heading: 'Problem', text: 'Power Play scored cones on poles of varying height. Our first robot, "Valkyrie", used a horizontal intake extension with grabbers, a transfer to a scoring grabber, and a 350° turret with gantry on a vertical lift. It went 2-3-0 at its first event in November; the handoff was slow and inconsistent, autonomous goals were out of reach, and it could not adapt as we moved around the field for ownership points. We started over.' },
        { heading: 'Design', bullets: [
          'Two arms ("E" and "C", named for the hub each is wired to), each on a worm-gear turret with 270° of rotation, a first pivot on an industrial worm gearbox with 150° range and a counter-spring, a servo-driven cascading linear extension on two rack-and-pinion assemblies, and a third pivot that keeps the grabber parallel to the ground and can flip a cone to score backwards.',
          'One arm intakes while the other scores, so there is no transfer and cycle time halves to about 4 s. From one "golden spot" in front of the substation the robot reaches ten junctions.',
          'Grabbers: double-helical gears for minimum backlash, surgical tubing inside for grip, a funnel-shaped interior, and enough over-extension to sit outside the substation and grab immediately. Linkage versions slipped on curved ends or did not fit in 18 in. A Delrin guide plate under the grabber aligns it to the pole for autonomous.',
          'Drivetrain: GoBilda Strafer-based chassis that splits into two halves on 300 mm Misumi slides — about 5 ft end to end — with a center lock that holds it together when collapsed to 18×18 in. Ground clearance was cut to 0.3 in for a low center of gravity when the arms are out.',
        ]},
        { heading: 'Iteration', text: 'The first two-arm robot used a "bent arm" with an elbow as the second pivot. It had reach and speed but little control: the 4 ft arms tangled with each other and hit field elements, and since the elbow was servo-driven we only knew its target, never its actual position or velocity — one collision broke an arm. Replacing the elbow with the rack-and-pinion extension put the main servos and motors on different axes and made the arm profilable. Delrin couplers on the first-pivot worm gearbox stripped, so we moved to GoBilda REX shafts and a JB-welded metal adapter to remove backlash.' },
        { heading: 'Controls', bullets: [
          'Inverse kinematics: the driver (or autonomous) supplies turret angle, first-pivot angle, and extension length; code resolves servo and motor positions and holds the third pivot level.',
          'Absolute linear potentiometers on the turret and first pivot give a zero at opmode start; since the hubs read them non-linearly, a calibration sweep builds a lookup table from encoder position to potentiometer voltage.',
          'Motion profiling for big moves: retract, pitch pivot 1 toward the ceiling, turn the turret, then lower and extend — so two 4 ft arms never cross.',
          'HuskyLens on each arm detects poles; a drivetrain camera reads the signal sleeve.',
        ]},
        { heading: 'Outcome', text: 'Phoenix debuted Jan 14 at 5-0-0, won the NTX Regional Championship with the Innovate Award, and reached the Ochoa Division Finals at the World Championship, winning the Innovate Award there too. Design reviews along the way came from SpaceX McGregor engineers (arm bounce, passive pole guides), BattleBots winner Jason Bardis (backlash, stabilizing the split drivetrain), and Nokia.' },
      ],
      images: [
        { src: 'assets/img/powerplay/00-phoenix-cutout.jpg', fit: 'contain', alt: 'Phoenix with both arms raised', caption: 'Phoenix — two three-pivot arms, each on a worm-gear turret' },
        { src: 'assets/img/powerplay/00-phoenix-arms-raised-cad.jpg', fit: 'contain', alt: 'Phoenix with both arms raised', caption: 'Phoenix — both arms raised, worm-gear turrets visible' },
        { src: 'assets/img/powerplay/01-arm-cad.jpg', fit: 'contain', alt: 'CAD of the multi-DOF arm with claw', caption: 'Arm linkage + claw — yaw axis and first pivot on worm gearboxes' },
        { src: 'assets/img/powerplay/02-robot-cad.jpg', alt: 'Full robot CAD with arm extended', caption: 'Full assembly, arm extended' },
        { src: 'assets/img/powerplay/03-competition.jpg', alt: 'Robot scoring a cone at competition', caption: 'Scoring at competition' },
        { src: 'assets/img/powerplay/04-built-robot.jpg', alt: 'Built robot with blue 3D-printed parts', caption: 'Original dual-extension build' },
        { src: 'assets/img/powerplay/05-practice-field.jpg', alt: 'Robot on practice field', caption: 'Practice field testing' },
        { src: 'assets/img/powerplay/06-single-arm-cad.jpg', fit: 'contain', alt: 'Single arm with worm gearbox and linear extension', caption: 'One arm: turret, worm-gear first pivot, rack-and-pinion extension, third pivot' },
        { src: 'assets/img/powerplay/08-split-drivetrain-electronics-cad.jpg', fit: 'contain', alt: 'Split drivetrain with electronics', caption: 'Drivetrain halves with hubs — one arm per hub' },
        { src: 'assets/img/powerplay/09-claw-sensor-cad.jpg', fit: 'contain', alt: 'Claw open with distance sensor', caption: 'Double-helical-gear grabber with distance sensor' },
        { src: 'assets/img/powerplay/10-anatomy-cad.jpg', fit: 'contain', alt: 'Labeled overview of Phoenix', caption: 'Annotated overview' },
        { src: 'assets/img/powerplay/11-phoenix-stowed-cad.jpg', fit: 'contain', alt: 'Phoenix stowed, arms folded', caption: 'Collapsed to 18×18 in with center lock' },
        { src: 'assets/img/powerplay/12-arms-splayed-photo.jpg', alt: 'Phoenix with arms fully splayed on the field', caption: 'Full 13 ft span on the practice field' },
        { src: 'assets/img/powerplay/13-scrimmage-photo.jpg', alt: 'Scrimmage in a gym', caption: 'Scrimmage' },
        { src: 'assets/img/powerplay/15-on-field-photo.jpg', alt: 'Phoenix on the Power Play field with arms deployed', caption: 'Arms deployed on the field' },
        { src: 'assets/img/powerplay/17-pivot-extension-cad.jpg', fit: 'contain', alt: 'Arm pivot and rack-and-pinion extension', caption: 'First pivot and cascading rack-and-pinion extension' },
        { src: 'assets/img/powerplay/18-arms-cad.jpg', fit: 'contain', alt: 'Both arms in CAD', caption: 'Both arms, stowed' },
        { src: 'assets/img/powerplay/19-phoenix-build-photo.jpg', alt: 'Phoenix during the build', caption: 'Phoenix, built' },
        { src: 'assets/img/powerplay/16-match-photo.jpg', alt: 'Phoenix during a match', caption: 'Match play' },
      ],
      links: [
        { label: 'Dual-extension test video', href: 'https://drive.google.com/file/d/1bxeMuue50E1q7UYErDWuo7Bku9uY2TJi/view' },
        { label: 'Rack & pinion arm video', href: 'https://drive.google.com/file/d/1WURUEpw_ZJW0e3rRzHhwmaQR8T6Pjgwo/view' },
        { label: 'Behind the Bot (FUN)', href: 'https://youtu.be/HBBmBNJ_7LY' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2022' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/phoenix' },
      ],
    },
    {
      id: 'bwsi-sar',
      aiUse: 'none',
      title: 'UAV Synthetic Aperture Radar — MIT BWSI',
      date: 'Summer 2024',
      role: 'Student, UAS-SAR track',
      categories: ['Aerospace', 'Software'],
      tags: ['Python', 'NumPy', 'Matplotlib', 'Pandas', 'PulsON 440', 'DJI F550', 'Signal processing'],
      summary: 'Mounted a PulsON 440 radar on a DJI F550 and wrote a vectorized back-projection algorithm to image obscured objects from radar scans along the flight path.',
      facts: [
        { label: 'Program', value: 'MIT Beaver Works Summer Institute' },
        { label: 'Radar', value: 'PulsON 440 UWB' },
        { label: 'Positioning', value: 'IR motion capture' },
      ],
      sections: [
        { heading: 'Concept', text: 'A UAV flying past a scene collects radar returns from many positions, synthesizing a much larger aperture than the physical antenna. Noise adds destructively across scans, so the combined image is cleaner than any single one.' },
        { heading: 'Pipeline', bullets: [
          'Range-Time-Intensity (RTI) plots to calibrate the radar before anything fancier; an RTI-delta plot (difference between consecutive scans) highlights moving targets.',
          'Back-projection: choose the image area and resolution, then for every pixel and every scan, find the distance from the UAV (from mocap) to that pixel and accumulate the return intensity at that range. Written with NumPy vectorized ops to keep it fast.',
          'Pandas to ingest and filter the IR motion-capture stream; Matplotlib for all plots and image display.',
        ]},
        { heading: 'Result', text: 'Resolved all four soda cans in the test scene despite two extremely bright retroreflectors next to them. The drone code led the cohort; the radar code lagged and got debugged the night before the flight test.' },
      ],
      images: [
        { src: 'assets/img/sar/01-rti-plot.jpg', fit: 'contain', alt: 'Range-time-intensity plot', caption: 'Range-Time-Intensity plot' },
        { src: 'assets/img/sar/05-backprojection.jpg', alt: 'Back-projection SAR image of reflectors', caption: 'Back-projected image — dots mark true reflector positions' },
        { src: 'assets/img/sar/02-rti-delta.jpg', alt: 'RTI delta plot', caption: 'RTI delta — moving objects pop out' },
        { src: 'assets/img/sar/03-rti-annotated.jpg', alt: 'Annotated RTI plot', caption: 'Annotated RTI' },
        { src: 'assets/img/sar/04-simulated-points.jpg', alt: 'Simulated five-point target', caption: 'Simulated five-point target for validating back-projection' },
        { src: 'assets/img/sar/06-flight-test.jpg', alt: 'Netted indoor flight test area', caption: 'Indoor flight test range' },
      ],
      links: [
        { label: 'Flight demo', href: 'https://docs.google.com/videos/d/1nTDq4MYMFNl97QRyq96pn62LJCfdCmdN-ImJtG1f_Ok/edit' },
      ],
    },
    {
      id: 'pickleball-robot',
      aiUse: 'llm',
      title: 'PickleBallDrone — Autonomous Ball-Retrieval Robot',
      date: 'May 2025 – present',
      role: 'Solo project',
      featured: true,
      categories: ['Robotics', 'Software'],
      tags: ['Jetson Orin Nano', 'Arduino Nano', 'RealSense D435', 'OpenCV', 'AprilTag', 'X-drive', 'Euler integration'],
      summary: 'A holonomic ground testbed that detects a served pickleball on an Intel RealSense D435, predicts its landing point with a drag-corrected physics rollout into a 20 cm target zone, and drives there on AprilTag localization. Long-term goal is a UAV that retrieves practice serves.',
      facts: [
        { label: 'Compute', value: 'Jetson Orin Nano → Arduino Nano over 115200 baud serial' },
        { label: 'Detection', value: '640×480 depth + color @ 30 FPS · 0.28–3.2 m working band' },
        { label: 'Prediction', value: '50-step × 0.1 s Euler rollout (5.0 s horizon) → 20 cm radius target zone' },
        { label: 'Not measured', value: 'motor free speed, AprilTag rate and accuracy — never instrumented' },
      ],
      sections: [
        { heading: 'Why', text: 'I like pickleball and am bad at it, and practice needs a partner. The plan is a UAV that takes off from the court and retrieves practice serves; the X-drive ground base is a cheap testbed for the whole perception-and-intercept stack before buying an expensive airframe.' },
        { heading: 'Perception', bullets: [
          'Detection methods tried: HSV filtering, RGB contour, circularity filtering, depth-discontinuity, and YOLO. HSV won — the pipeline blob-detects on saturation and brightness, then samples a depth pixel from the RealSense depth map. Circularity was dropped because motion blur breaks it; the other three were dropped without the reason being logged.',
          'Localization methods tried: global-shutter VSLAM, T265 VSLAM, optical flow, and AprilTag. AprilTag won — "the most accurate by far" — on an 800×600 @ 90 FPS stream with a 0.146 m tag. The measured rate and accuracy were never recorded, so that ranking is qualitative, not quantitative.',
          'The T265 path carried its own outlier rejection with "drift likely" warnings before it was dropped.',
        ]},
        { heading: 'Trajectory prediction', text: 'Ball samples arrive roughly 33 ms apart. A kinematic fit over a sliding 5–16-point window — with the last 3 points weighted 100× — solves initial position and velocity, then a 50-step Euler integration with drag and gravity finds where the ball meets the ground plane. A single drag coefficient failed because of Magnus effect; splitting it into horizontal (1) and vertical (4.0) coefficients matched real flights, with the true landing point falling inside the 20 cm target zone. Ball model: m = 0.026 kg, r = 0.0365 m.' },
        { heading: 'Control', text: 'A P controller on the Jetson computes power as 200 × position error in metres, capped at 255 PWM, driving toward a point 1.0 m in front of the tag. The Arduino sketch converts that angle-and-power command into PWM for the four X-drive motor controllers.' },
        { heading: 'Failure modes and what is unknown', bullets: [
          'No heading control — the Arduino sketch assumes a fixed robot heading, and the orchestrator flags its own dead reckoning as applying linear deltas without accounting for rotation. Closing that loop is the next milestone.',
          'Multi-tag ambiguity: seeing more than one AprilTag aborts pose estimation outright.',
          'The detection → trajectory → drive pipeline runs on recorded data; live end-to-end integration is still pending.',
          'Measured detection throughput, motor free speed, and AprilTag accuracy are all unknown — not estimated, just never instrumented.',
        ]},
      ],
      images: [
        { src: 'assets/img/pickleball/01-chassis-electronics.jpg', alt: 'Chassis with Jetson, T265, global shutter camera, Arduino', caption: 'Testbed electronics — Jetson Orin Nano, T265, global-shutter cam, Arduino Nano' },
        { src: 'assets/img/pickleball/03-trajectory-prediction.jpg', fit: 'contain', alt: 'Predicted ball trajectory with target zone', caption: '23 recorded ball positions, parabolic fit, drag-corrected rollouts, and the 20 cm target zone' },
        { src: 'assets/img/pickleball/02-ball-detection.jpg', alt: 'Three-pane ball detection view', caption: 'Live detection: raw depth, raw colour, and the HSV-filtered mask with the ball’s 3D position' },
        { src: 'assets/img/pickleball/04-realsense-court.jpg', alt: 'RealSense capture on a court at night', caption: 'Court capture at night — RGB beside its colorized depth map' },
        { src: 'assets/img/pickleball/05-realsense-indoor.jpg', alt: 'Indoor RealSense RGB and depth pair', caption: 'Indoor capture used for pipeline development' },
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/Randomfalcon124/PickleBallDrone-main' },
        { label: 'Ball detection demo', href: 'https://drive.google.com/file/d/1HRkXoVJWfmUpVvsF8ZYCf25goq4tGFhf/view' },
        { label: 'Trajectory prediction demo', href: 'https://drive.google.com/file/d/1ghIXcx0HapQh7FFHHHO9YrD25-o6ufu3/view' },
        { label: 'Robot control demo', href: 'https://drive.google.com/file/d/11jU2Om0csPG5VMqSasA9x8ZPP-slJiSK/view' },
      ],
    },
    {
      id: 'window-counter',
      aiUse: 'claude',
      title: 'Autonomous Window-Counting House Robot',
      date: '2025 – present',
      role: 'Solo project',
      categories: ['Robotics', 'Software'],
      tags: ['ROS 2', 'Nav2', 'RTAB-Map', 'nvblox', 'Jetson Orin Nano', 'OWLv2', 'Frontier exploration', 'systemd'],
      summary: 'A wheeled robot that explores a house unsupervised, builds a persistent map, and counts its windows — 13 distinct windows (range 11–15) from 2,156 frames, with real-time nav on an 8 GB Jetson and the heavy vision models offloaded to a laptop GPU over SSH.',
      facts: [
        { label: 'Compute', value: 'Jetson Orin Nano 8GB (nav) + RTX 4060 laptop (vision, over SSH)' },
        { label: 'Best measured result', value: '13 distinct windows, range 11–15, from 2,156 frames' },
        { label: 'Nav accuracy', value: '0.685 m goal reached within 0.067 m · ~0.02 m on closed-loop 0.5 m legs' },
        { label: 'Detection fusion', value: '90,360 / 28,344 / 82,460 raw detections → 105 candidates at ≥2-model agreement' },
      ],
      sections: [
        { heading: 'Stack', bullets: [
          'RTAB-Map for the persistent map and loop closure, Intel T265 for 6-DOF visual odometry, nvblox TSDF for volumetric fusion.',
          'Nav2 with an MPPI controller planning over 2.5 cm costmaps — 6×6 m rolling local, 8×8 m global — fed by a monocular depth pipeline rather than a lidar.',
          'Yamauchi frontier exploration issues one NavigateToPose goal at a time at 2 Hz with a decaying frontier blacklist.',
          'Room segmentation by morphological opening keeps the robot sweeping a room\'s walls (≥2 vantage points, coverage ≥ 0.85) before it leaves through a doorway — 20/20 offline tests.',
        ]},
        { heading: 'Perception', text: 'Window detection is a multi-model consensus: OWLv2, OWL-ViT, and GroundingDINO each run the full 2,156-frame sweep (~38 min on the 4060), a ≥2-model agreement rule cuts them to 105 candidates, and SIFT-homography dedup merges re-sightings of the same physical window. NVIDIA Cosmos Reason then acts as a VLM skeptic, confirming or refuting each candidate at about 25 s per frame. Obstacles come from Depth-Anything-V2 metric depth, height-classified against a fitted ground plane — 17/17 offline tests.' },
        { heading: 'Safety architecture', text: 'The robot ships disarmed: with no arm token on disk the velocity branch idles and nothing moves. A safety governor issues a go/no-go permit at up to 50 Hz, failing toward stop, and the robot daemon enforces per-tick gates — arm token, permit, heartbeat, epoch, and an anti-ram reflex that halts when power is applied but the T265 reports no translation. A systemd unit auto-starts the stack on boot and a health-gated watchdog re-runs bringup every 90 s, so power cuts self-heal.' },
        { heading: 'What failed', bullets: [
          'Nav2 rammed a desk because the 2D costmap was blind to the overhang — hence the daemon-side anti-ram reflex.',
          'Nav2 silently dropped an entire obstacle cloud: per-source max_obstacle_height defaults to 0.0 and does not inherit the layer value. One explicit param fixed it.',
          'With zero obstacle points Nav2 could not raytrace-clear free space, so the map read lethal. Publishing a clearing-only free-space cloud took free cells from 85 to 2,347 (21/21 tests).',
          'Running every model on the Jetson drove load average to 10 and starved the planner — pausing the detector restored planning, which is what forced the split-compute architecture.',
          'Glossy-floor phantom obstacles only died with a literal 2.5 cm mesh-projection costmap plus a left-right-consistency stereo filter.',
          'After a full house loop, RTAB-Map loop closure snapped roughly 1.8 m of accumulated odometry drift in a single map→odom correction.',
        ]},
      ],
      images: [
        { src: 'assets/img/window-counter/01-floorplan-reconstructed.jpg', alt: 'Reconstructed floor plan of the house', caption: 'Floor plan built from camera alone — rooms coloured by visit frequency, window hypotheses placed on walls' },
        { src: 'assets/img/window-counter/04-confirmed-windows-montage.jpg', alt: 'Montage of confirmed window detections', caption: 'The evidence behind the count of 13 — each confirmed window in room context' },
        { src: 'assets/img/window-counter/02-exploration-graph.jpg', fit: 'contain', alt: 'Topological exploration graph', caption: 'Exploration graph — rooms with visit counts, traversed vs frontier edges' },
        { src: 'assets/img/window-counter/03-window-detections-grid.jpg', alt: 'Grid of multi-model window detections', caption: 'Multi-model detections with boxes and confidence scores, before consensus filtering' },
        { src: 'assets/img/window-counter/06-depth-to-costmap.jpg', fit: 'contain', alt: 'Monocular depth converted to a Nav2 costmap', caption: 'Depth-Anything-V2 metric depth (left) → Nav2 occupancy costmap (right, red = occupied)' },
        { src: 'assets/img/window-counter/07-sfm-trajectory-map.jpg', fit: 'contain', alt: 'Structure-from-motion trajectory map', caption: 'Top-down SfM map from 93 frames — wall points plus the camera path' },
        { src: 'assets/img/window-counter/08-robot-eye-view.jpg', alt: 'Onboard camera view of the foyer', caption: 'What the robot sees — foyer with the AprilTag localization marker' },
      ],
    },
    {
      id: 'neuron',
      aiUse: 'claude',
      title: 'VGTransformer — Abstention by Architecture',
      date: 'May 2026 – present',
      role: 'Solo research project',
      categories: ['Research', 'Software'],
      tags: ['PyTorch', 'Transformers', 'Uncertainty', 'LoRA', 'Qwen2.5', 'GPT-2', 'AbstentionBench', 'Calibration'],
      summary: 'A transformer that carries a scalar confidence value alongside every token and vetoes its own output head when confidence falls below a learned threshold — silence wired into the forward pass instead of prompted. It works completely on a toy task and fails at 1.5B.',
      facts: [
        { label: 'Architecture', value: '4 × (V-layer, G-layer) — GPT-2 blocks alternating with diagonal per-neuron gates' },
        { label: 'Parameters', value: '800,769 — the G-layers add 1,536 (+0.19%)' },
        { label: 'Toy result', value: '405/405 unanswerables silenced · 288/288 deterministic answerables correct' },
        { label: 'AbstentionBench (1.5B)', value: 'silence-signal AUROC 0.489–0.544 — essentially chance' },
      ],
      sections: [
        { heading: 'Mechanism', text: 'A G-layer owns three vectors (τ, α, β ∈ ℝ¹²⁸) and no weight matrix. Per neuron it computes a margin against τ, gates on |v| with a sigmoid, and reports c_local as the soft fraction of neurons that fired. Confidence propagates by min, not product — c_out = min(c_in, c_local) — and c_final below the learnable τ_out (init 0.5, final 0.308 on a seed-0 re-run) means silence. Loss is L_pred + 0.1·(L_gate + L_silence + L_unknown).' },
        { heading: 'The load-bearing-silence result', text: 'With an unknown-answer token in the vocabulary, the model just learned that token by plain cross-entropy, c_final saturated near 1, and the confidence channel went vestigial — a token-based "I don\'t know" is always the cheaper gradient path. The channel only learned once the token was removed and silence became the only mechanism. Two other collapses shaped the design: gating on c itself is positive feedback driving c → 0 at any depth (fixed by gating on |v|), and multiplicative c chaining collapses unconditionally (fixed by min).' },
        { heading: 'What the toy task shows', text: 'On a 41-token vocab with 7 deterministic, 3 ambiguous, and 16 unanswerable entities over 1,500 steps: 100% correct on deterministic, 100% silenced on unanswerable, and voluntary silence on ambiguous items with no loss term targeting it — the README reports ~38%, my re-run 73.8% (93/126), so the direction replicates but the magnitude is seed-sensitive. G-layer silence rates specialize by depth ([0.68, 0.75, 1.00, 0.75]), but per-neuron τ variance stays flat at ±3% — an honest miss.' },
        { heading: 'The negative result at scale', bullets: [
          'Four Qwen2.5-1.5B LoRA variants over 1,500 AbstentionBench samples: silence-signal AUROC 0.489–0.544, no variant above 0.55. Answerable accuracy 30.2–32.2%; per-source AUROC ranges from 0.28 (QASPER) to 0.81 (BBQ). The signal did not transfer to realistic unanswerability.',
          'GPT-2-XL VG variant on 447 val questions, 2 seeds: baseline 13.0% EM; sweeping τ_out gives 46.2% EM at 5.8% coverage (seed 1) vs 33.3% at 5.4% (seed 2). Consistent in direction, not magnitude.',
          'Plain log-prob thresholding is the baseline the architectural signal failed to beat: dense distillation takes TriviaQA from 35.8% strict EM to 84.7% at 17% coverage, and NQ Open from 17.2% to 66.7% at 7.2%.',
        ]},
        { heading: 'Limitations', text: 'The toy experiments validate that an architectural confidence channel can implement abstention when silence is the only path, that magnitude-gating and min-composition are necessary, and that layer-level specialization emerges. They do not validate per-neuron τ specialization — the variance is flat, so only layer-level calibration is claimed. Nothing validates the mechanism at scale: the 1.5B results are near chance and GPT-2-XL is 447 samples with seed variance, not superiority over log-prob baselines. The toy task has 26 entities — proof of mechanism, not generalization. Next steps are G-layers trained from scratch at 100M–1B rather than LoRA retrofits, and a matched-compute head-to-head against linear probes and semantic entropy.' },
      ],
      images: [
        { src: 'assets/img/neuron/02-c-final-histogram.jpg', fit: 'contain', alt: 'Histogram of c_final by answerability', caption: 'The key result: c_final separates the three regimes with no overlap, and learned tau_out lands between them' },
        { src: 'assets/img/neuron/01-architecture.jpg', fit: 'contain', alt: 'VGTransformer architecture diagram', caption: 'V/G stack — residual stream left, confidence rail right, tau_out vetoing the output head' },
        { src: 'assets/img/neuron/05-abstentionbench-auroc.jpg', fit: 'contain', alt: 'AbstentionBench AUROC by variant', caption: 'The scaling failure, unrounded: no 1.5B variant beats 0.55 AUROC' },
        { src: 'assets/img/neuron/03-training-curves.jpg', fit: 'contain', alt: 'Training loss curves', caption: 'All four loss components train down jointly; L_gate stays non-zero because ambiguity keeps pressure alive' },
        { src: 'assets/img/neuron/04-gpt2xl-vg-pareto.jpg', fit: 'contain', alt: 'GPT-2-XL accuracy vs coverage', caption: 'Confidence ranks correctness on GPT-2-XL — consistent in direction across seeds, not magnitude' },
        { src: 'assets/img/neuron/06-selective-pareto.jpg', fit: 'contain', alt: 'Selective prediction Pareto curve', caption: 'Plain log-prob selectivity — the baseline the architectural signal failed to beat' },
        { src: 'assets/img/neuron/07-guard-fp-analysis.jpg', fit: 'contain', alt: 'False-positive rate analysis', caption: 'Tooling side-project audit: the loose estimate over-counted the fire rate about 6×' },
      ],
    },
    {
      id: 'defiant',
      title: '"Defiant" — Flip-Arm Turret Robot, FTC Freight Frenzy',
      date: '2021 – 2022',
      role: 'Designer & builder',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Master sketches', 'Belt cascade', 'Turret', 'Butterfly drivetrain', 'Tape measure', 'JVN calcs'],
      summary: 'My first full season in Fusion 360: a flipping intake arm that mirrors the robot red-to-blue mid-match, a belted 30 in cascade extension, and a drivetrain that drops four extra torque wheels to win shoving matches.',
      facts: [
        { label: 'Result', value: 'Worlds Jemison div. rank 2 (7–1) · Championship Think Award 3rd' },
        { label: 'Season', value: '60–5–0 quals · 7 event wins · Alabama State + TX-North champions' },
        { label: 'np-OPR', value: '222.5 — #1 of 4,404 teams worldwide' },
        { label: 'Extension', value: '3× 200 mm Misumi slides → 30 in, 0.5 s full stroke' },
        { label: 'Drivetrain', value: '14.2:1 mecanum + retractable traction wheels' },
      ],
      sections: [
        { heading: 'Dual-sided intake arm', text: 'Scoring from the wall with side-depositing slides meant we had to intake from either the red or blue side. Instead of two intakes or rotating the slides, we fixed the elevator and put the intake on an arm that flips over the robot — one mechanism acting as two intakes, and the robot mirrors sides in seconds. JVN calculations put the arm at ~100:1 for sub-0.5 s swings; a REV UltraPlanetary version was scrapped for gearbox slack.' },
        { heading: 'Turret intake', text: 'Silicone-tube intake on an internal 360° turret, feeding a polycarbonate hopper sized for exactly one freight so a second piece gets ejected before it can become a penalty. Power comes through miter gears and chain from the arm channel. The same motor also drives the carousel wheel via a belt, so duck scoring costs no extra actuator.' },
        { heading: 'Horizontal linear extension', text: 'Three 200 mm Misumi slides cascaded with belts on custom 3D-printed pulley mounts: 30 in of reach that fully extends or retracts in about half a second. V1 (mixed 200/300 mm slides) failed on weak mounts and unsupported idlers and did not fit the size box.' },
        { heading: 'Drivetrain', text: 'Bigger robots could shove us off the shared hub. Fix: keep the fast 14.2:1 mecanum base and add four retractable traction wheels that drop only when we need to push back — the "butterfly" drivetrain. Earlier high-clearance chain versions lost tracking precision and suffered encoder interference from motors mounted too close together.' },
        { heading: 'Scoring grippers & capping', bullets: [
          'Custom 3D-printed claws on a two-bar linkage (GoBilda SuperSpeed servo) that hold cubes, balls, and ducks and drop them on any hub level — after a scoring box and a three-point linkage both proved too slow or too weak.',
          'Capping via a servo-driven tape-measure extension with pan/tilt; the magnet concept was discarded because it pulled weighted freight off the hub.',
          'Lesson: capping only pays if it does not cost cycles, so we cap while delivering ducks.',
        ]},
      ],
      images: [
        { src: 'assets/img/defiant/00-defiant-cutout.jpg', fit: 'contain', alt: 'Defiant with tape-measure turret and intake arm', caption: 'Defiant — flip-over intake arm, cascade extension, tape-measure capper' },
        { src: 'assets/img/defiant/02-drivetrain-photo.jpg', alt: 'Built butterfly drivetrain, side view', caption: 'Butterfly drivetrain as built — mecanum pods with retractable traction wheels' },
        { src: 'assets/img/defiant/03-cascade-extension-cad.jpg', alt: 'Cascade linear extension CAD', caption: 'Belted cascade extension — 3× 200 mm slides, 30 in reach' },
        { src: 'assets/img/defiant/04-drivetrain-underside-cad.jpg', alt: 'Drivetrain underside CAD showing motors', caption: 'Underside — motor placement after encoder-interference lesson' },
        { src: 'assets/img/defiant/05-tape-measure-turret-cad.jpg', alt: 'Tape-measure turret spool CAD', caption: 'Tape-measure capping turret — spool, pan and tilt' },
        { src: 'assets/img/defiant/06-intake-bucket-cad.jpg', alt: 'Intake bucket with servo door CAD', caption: 'One-freight hopper with servo door' },
        { src: 'assets/img/defiant/07-extension-motor-cad.jpg', alt: 'Extension module with motor CAD', caption: 'Extension drive module' },
        { src: 'assets/img/defiant/08-robot-front-photo.jpg', alt: 'Robot front with intake', caption: 'Defiant, front' },
        { src: 'assets/img/defiant/09-full-robot-render.jpg', alt: 'Full robot render', caption: 'Full robot render' },
        { src: 'assets/img/defiant/10-worlds-field-photo.jpg', alt: 'Defiant on the World Championship field', caption: 'On the field at the 2022 World Championship' },
        { src: 'assets/img/defiant/12-match-photo.jpg', alt: 'Defiant mid-match with freight', caption: 'Mid-match' },
      ],
      links: [
        { label: 'Defiant reveal video', href: 'https://youtu.be/c_Lumfw_asU' },
        { label: 'Behind the Bot (FUN)', href: 'https://youtu.be/Q2nJBSsAp2c' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2021' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/defiant' },
        { label: 'Team page', href: 'https://www.ftc7172.org' },
      ],
    },
    {
      id: 'nautilus',
      cardImage: 8,
      title: '"Nautilus" — Passive-Claw Specimen Robot, FTC Into the Deep',
      date: '2024 – 2025',
      role: 'Lead designer',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Belted slides', 'Worm gear', 'Passive claw', 'Swyft modules', 'Color sensor', 'Delrin'],
      summary: 'A specimen scorer that grabs and scores with zero actuators — a geared two-way claw with a mechanical hard stop — plus a 2.6 ft belted elevator with a 90° tilt so samples never need a transfer.',
      facts: [
        { label: 'Result', value: 'FiT-North Regional Champion (alliance captain) + Control Award' },
        { label: 'Worlds', value: 'Franklin div. rank 14 (7–3) · Connect Award' },
        { label: 'Season', value: '50–18–2 quals · 5 event wins · np-OPR #8 in Texas' },
        { label: 'Elevator', value: '2.6 ft belted slides with a 90° tilt' },
        { label: 'Auto', value: '6-specimen autonomous' },
      ],
      sections: [
        { heading: 'Specimen scorer', text: 'Early versions were a vertical extension, then a scissor claw with an active latch — three degrees of freedom, slow, unstable when extended backwards. The fix was to remove actuation: a geared passive claw with a 180° lateral pivot grabs a specimen off the wall just by driving into it, and a mechanical hard stop ends claw motion so scoring is pure drive. Claw geometry was tuned (with the math on the page) so the passive action could not shear a servo spline.' },
        { heading: 'Intake', text: 'Four iterations: tri-claw → dual tubing → trapdoor → 3D-printed pincer claw. The pincers open ~3 in to pull from crowds, oscillate between parallel and perpendicular for angled samples, and sit on a 360° pivot. A REV v3 color/distance sensor rejects opposing-alliance samples and triggers automatic drive to the drop position; inverse trigonometry maps joystick motion to claw pose.' },
        { heading: 'Elevator and tilt', text: 'Belted Swyft slides with 2.6 ft of reach into any side of the submersible. The 90° tilt eliminates a sample transfer entirely. A worm-gear tilt was slow and shredded gears, so it moved to spur + pinion; 13.7:1 and 5.2:1 motors could not balance torque and speed at full extension, so a 60:36 reduction on a 5.2:1 motor was used. The extension motor is coaxial to cut tipping and the lift is counter-sprung.' },
        { heading: 'Drivetrain, pushbar, hang', bullets: [
          'Swyft direct-drive modules: more space in the middle of the chassis, quick to swap if one breaks, enough ground clearance to drive over samples.',
          'Servo pushbar shoves pre-set samples into the observation zone during autonomous.',
          'Level-3 hang from separate Delrin hooks on the slides, each on its own servo, fitting inside the corners of the robot.',
        ]},
        { heading: 'Process', text: 'Subsystems were built to be removable and tested individually before integration; a test program exercised each mechanism and an odometry calibration routine reset pose before every match. Timeline: kickoff prototypes in September, Swyft drive and Misumi elevator by October, color-sensor specimen detection in November, 5-specimen auto in December, trapdoor and double-slide elevator in February, L3 hang and pincer claw in March.' },
      ],
      images: [
        { src: 'assets/img/nautilus/01-robot-cad.jpg', alt: 'Nautilus full robot CAD render', caption: 'Nautilus — full assembly' },
        { src: 'assets/img/nautilus/02-elevator-extended-cad.jpg', alt: 'Nautilus with elevator fully extended', caption: 'Elevator at full 2.6 ft extension with 90° tilt' },
        { src: 'assets/img/nautilus/04-specimen-claw-cad.jpg', fit: 'contain', alt: 'Passive specimen claw on vertical slide', caption: 'Passive two-way specimen claw — grabs and scores by driving' },
        { src: 'assets/img/nautilus/10-specimen-scorer-cad.jpg', fit: 'contain', alt: 'Specimen scorer raised', caption: 'Specimen scorer at scoring height — 180° lateral pivot' },
        { src: 'assets/img/nautilus/11-intake-arm-cad.jpg', fit: 'contain', alt: 'Nautilus intake arm', caption: 'Intake arm on its pivot' },
        { src: 'assets/img/nautilus/03-drivetrain-cad.jpg', fit: 'contain', alt: 'Swyft-module mecanum drivetrain CAD', caption: 'Swyft direct-drive mecanum chassis' },
        { src: 'assets/img/nautilus/05-extension-hooks-cad.jpg', fit: 'contain', alt: 'Extension slides with Delrin hang hooks', caption: 'Slides with Delrin L3 hang hooks' },
        { src: 'assets/img/nautilus/06-carriage-sprocket-cad.jpg', fit: 'contain', alt: 'Slide carriage with sprocket and bearings', caption: 'Slide carriage — sprocket and bearing stack' },
        { src: 'assets/img/nautilus/07-gripper-closeup-cad.jpg', alt: 'Gripper close-up render', caption: 'Pincer intake close-up' },
        { src: 'assets/img/nautilus/08-team-robot-photo.jpg', alt: 'Team with Nautilus at competition', caption: 'Team 7172 with Nautilus' },
        { src: 'assets/img/ftc7172/03-nautilus-2025.jpg', alt: 'Nautilus on the Into the Deep field', caption: 'Nautilus on the field' },
      ],
      links: [
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2024' },
        { label: 'Robot page', href: 'https://www.ftc7172.org/robots/nautilus' },
      ],
    },
    {
      id: 'athena',
      title: '"Athena" — Tilting-Elevator Pixel Robot, FTC Centerstage',
      date: '2023 – 2024',
      role: 'Lead designer',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Misumi slides', 'Lead screws', 'Rack & pinion', 'Over-center linkage', 'TPU', 'Pure Pursuit'],
      summary: 'A compact mecanum robot whose belted elevator rides on lead-screw tilt so it can score any backdrop row without being parallel to it — plus a two-pixel compliant scorer, a rail-launched drone, and a lead-screw hang.',
      facts: [
        { label: 'Result', value: 'Area Champion (6–0) + Control Award · TX State div. finalist · MTI Finalist' },
        { label: 'Season', value: '41–3–0 quals · undefeated through league play · U² Tournament winner + Inspire' },
        { label: 'np-OPR', value: '182.7 — #1 of 732 in Texas, #9 of 6,664 worldwide' },
        { label: 'Elevator', value: '2× 300 mm 3-stage Misumi, 0.5 s stroke' },
      ],
      sections: [
        { heading: 'Drivetrain', text: 'Four 13.7:1 GoBilda motors direct-driving mecanums on custom side plates, sized to clear pixels underneath and thread the trusses and stage door. V1 on the 384 mm GoBilda kit had no mounting room; V2 was 24 mm wider and ran two league meets before it proved slower and harder to maneuver — the final chassis is smaller, lighter (easier hang), and crosses the field in about five seconds.' },
        { heading: 'Intake', text: 'Surgical-tubing intake on a 3.7:1 motor, mechanically limited to two pixels, that grabs pixels in any orientation including standing up and from the stacks. An over-center linkage holds the intake lifted for transfer with no power. The "bowtie" shape at the back of the intake is what positions pixels for a clean handoff; rotating the tubing sets 90° to each other was the biggest throughput gain. Compliant-wheel and side-sweeper versions were discarded for jamming and for failing to seat two pixels side by side.' },
        { heading: 'Elevator, tilt and gantry', text: 'Two parallel 3-stage 300 mm Misumi slides, belted, with the idler assembly on the driving-pulley shaft (V1 put idlers too far from the motor). The whole extension rests on an 8 mm shaft carried by lead screws on each side — the tilt — so it can reach any backdrop height and score from a distance, which speeds up autonomous. A rack-and-pinion gantry on a 5-turn SuperSpeed servo fine-positions the scorer between transfer and scoring.' },
        { heading: 'Scorer', text: 'Two micro-servo clamps in a printed frame hold two pixels and release them independently; ball switches in the base plate detect the backdrop and trigger auto-release, and the scorer hangs on surgical tubing so it complies when the robot is not parallel to the board. A TPU "pixel mover" on the gantry grabs the inside of a pixel to nudge mosaics. Side-pinch V1 was too bulky and the divider between pixels kept snapping.' },
        { heading: 'Endgame', bullets: [
          'Drone launcher: clamp-and-release carriage on an MGN9 linear rail, mounted on the hang mechanism for extra height; 56° total launch angle chosen after 10+ landings per version at 71°, 66°, and 56°.',
          'Hang: geared lead screws on 3.7:1 motors, both sides, hubs on 1 in bearings; Delrin hooks flip over the bar and the screws pull the robot up.',
        ]},
        { heading: 'Software', text: 'State machine (INTAKE → TRANSFER → SWING → EXTEND → SCORE → RETRACT) driven by sensors: HuskyLens for pixel stacks, webcam AprilTags for backdrop column alignment and localization cross-check, ultrasonic for stack distance, REV color sensor to auto-advance from intake to transfer. Custom Pure Pursuit with a per-segment lookahead radius, a DualPad class that merges both gamepads and adds shift keys, haptics on two pixels, and an LED preset display.' },
      ],
      images: [
        { src: 'assets/img/athena/00-athena-cutout.jpg', fit: 'contain', alt: 'Athena full robot', caption: 'Athena — tilting belted elevator, gantry, and two-pixel scorer' },
        { src: 'assets/img/athena/02-elevator-gantry-cad.jpg', fit: 'contain', alt: 'Elevator slides and gantry CAD', caption: 'Belted Misumi elevator with rack-and-pinion gantry' },
        { src: 'assets/img/athena/03-intake-tilt-cad.jpg', fit: 'contain', alt: 'Intake and tilt arm CAD', caption: 'Surgical-tubing intake on over-center lift' },
        { src: 'assets/img/athena/04-drivetrain-cad.jpg', fit: 'contain', alt: 'Drivetrain chassis CAD', caption: 'Compact direct-drive mecanum chassis' },
        { src: 'assets/img/athena/05-team-trophies.jpg', alt: 'Team with trophies and robot', caption: 'FiT-North Area Championship' },
        { src: 'assets/img/athena/06-build-session.jpg', alt: 'Two members working on the robot', caption: 'Build session' },
      ],
      links: [
        { label: 'Behind the Bot — Centerstage (FUN)', href: 'https://youtu.be/VW5LuiKfoOg' },
        { label: 'Season stats (FTCScout)', href: 'https://ftcscout.org/teams/7172?season=2023' },
      ],
    },
    {
      id: 'protein',
      aiUse: 'claude',
      title: 'Designing an Enzyme to Turn CO₂ into Solid Carbon',
      date: 'Apr 2026 – present',
      role: 'Solo research project',
      categories: ['Research', 'Software'],
      tags: ['AlphaFold3', 'Protein design', 'GFN2-xTB', 'Quantum chemistry', 'Kinetic Monte Carlo', 'Python', 'mmCIF'],
      summary: 'Six generations of computational design on an iron-storage scaffold, looping mutation → AlphaFold3 → geometry scoring → quantum chemistry until the diiron site came out at 3.91 Å. In silico only — no protein expressed, no gene ordered, no measurement made.',
      facts: [
        { label: 'Status', value: 'In silico only — nothing tested at a bench' },
        { label: 'Scaffold', value: 'E. coli bacterioferritin BfrB, 158 aa — lead is 2 mutations, A21F + I123W' },
        { label: 'Best AF3 fold', value: 'pTM 0.89 / ipTM 0.93 / ranking 0.92 · wild-type control 0.96' },
        { label: 'Fe–Fe distance', value: '3.91 Å against a 3–4 Å catalytic diiron target' },
      ],
      sections: [
        { heading: 'The design loop', text: 'Locking CO₂ into solid carbon normally needs furnaces at 700 °C or more; a protein doing it in water at room temperature would turn a waste gas into a structural material. A script mutates the sequence and emits AlphaFold3 job JSON; AF3 folds each variant with two Fe ions across five seeds; a parser reads the mmCIF and scores what actually matters — Fe–Fe separation, Fe–ligand contacts, ring angles — rather than the confidence score alone. Survivors are carved into an 82-atom QM cluster. The reject path ran six times.' },
        { heading: 'The error I carried for three generations', text: 'Generations 3–5 stalled at 0.37–0.62 confidence because I built the iron site from HxxH motifs — four histidines. Every natural diiron enzyme uses ExxH: two histidines and four glutamates, two of them bridging both metals. Without those bridges the irons drifted 20–30 Å apart and AF3 would not place the second at all. Gen6 restored the six native ligands (0.94, Fe–Fe 3.98 Å); gen6b added the aromatic cage in two mutations (0.92, 3.91 Å, mean pLDDT 96.2).' },
        { heading: 'Why the QM number is not quotable', text: 'The 82-atom cluster reproduces the AF3 geometry (Fe–Fe 3.909 Å, His–Fe 2.22/2.23 Å) with both irons five-coordinate, leaving an open substrate site. GFN2-xTB gives a CO₂ interaction energy of about −40.6 kcal/mol — favourable in sign, unreliable in magnitude: the adduct optimisation failed to converge with a HOMO–LUMO gap around 0.68 eV, single points needed Fermi smearing at 6000 K, the geometry is unrelaxed, and a semi-empirical method cannot describe transition-metal spin states. A PBE/def2-SVP GPU run returned +93,000 kcal/mol — garbage, all SCFs unconverged. The load-bearing number, the C–O cleavage barrier, is uncomputed.' },
        { heading: 'Nanotube growth — a 0% result', text: 'A kinetic Monte Carlo model grew tubes ring by ring from literature barriers. 0 of 200 trials produced a usable nanotube: mean 10.9 rings against a target of 50, mean defect fraction 0.22 against a 0.10 tolerance, and 185 trials terminated on defect accumulation. At 298 K, defect incorporation (85 kJ/mol) simply outcompetes ring closure (60 kJ/mol) — the most useful thing the model does is predict its own failure mode.' },
        { heading: 'Things I am not sure about', bullets: [
          'Two result files disagree on the KMC outcome — one says 0% completion, the other 40.5%. I plotted the former, the only one with raw per-trial data, and would not cite the optimistic number.',
          'In that same file, 15 trials are labelled as reaching the 50-ring target while the maximum recorded ring count is 49 — an apparent off-by-one.',
          'The CO₂ → nanotube claim chains precedented steps that have never been combined in one enzyme. My honest estimate of nanotube formation is low single digits.',
          'Next step is the ORCA barrier calculation — it is free and it can kill the project before any money is spent. Then a costed ladder: gene synthesis (~$200) → SDS-PAGE ($30) → Fe binding by UV-Vis ($5) → ferroxidase assay ($5) → oxidative coupling ($10) → CO₂ interaction ($20). About $270 answers whether the protein folds and holds two irons.',
        ]},
      ],
      images: [
        { src: 'assets/img/protein/02-gen6b-overview.jpg', fit: 'contain', alt: 'AlphaFold3 model of the gen6b design', caption: 'gen6b_tight, AF3 model 0, coloured by per-residue confidence (mean pLDDT 96.2)' },
        { src: 'assets/img/protein/04-gen6b-diiron-site.jpg', fit: 'contain', alt: 'Close-up of the engineered diiron site', caption: 'Active site — six native iron ligands plus the aromatic cage, Fe–Fe at 3.91 Å' },
        { src: 'assets/img/protein/03-confidence-progression.jpg', fit: 'contain', alt: 'Fold confidence across design generations', caption: 'gen3 → gen6b. The step change came from switching HxxH to the native ExxH ligand set' },
        { src: 'assets/img/protein/05-kmc-growth.jpg', fit: 'contain', alt: 'Kinetic Monte Carlo nanotube growth results', caption: '200 trials: rings per trial (left) and defect fraction (right) — only 15 fall under tolerance, none complete' },
        { src: 'assets/img/protein/01-design-loop.jpg', fit: 'contain', alt: 'Block diagram of the design loop', caption: 'The four-stage loop — the reject path ran six times' },
      ],
    },
    {
      id: 'ftc-7172',
      title: 'FTC 7172 Technical Difficulties — Five Seasons',
      date: '2021 – 2026',
      role: 'Captain & lead mechanical',
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Butterfly drivetrain', 'Turret', 'Linear extension', 'Sprung claw', 'Team leadership'],
      summary: 'Lead mechanical engineer across five robots — from a mecanum base with retractable traction wheels to the 2026 World Championship Finalist Alliance.',
      facts: [
        { label: 'My five seasons', value: '245–73–2 in qualification matches · 19 event wins · 63 awards' },
        { label: 'Best finish', value: 'FIRST Championship Finalist Alliance (2026)' },
        { label: 'World np-OPR rank', value: '#1 (2021–22) · #10 (2022–23) · #9 (2023–24)' },
        { label: 'Worlds appearances', value: '4 of 5 seasons — 2022, 2023, 2025, 2026' },
      ],
      sections: [
        { heading: 'Robots', bullets: [
          '2021–22 "Defiant" (Freight Frenzy): mecanum drivetrain with four retractable traction wheels for pushing matches; extending tape-measure turret; belted cascade extension reaching 30 in. Worlds Jemison division rank 2, Championship Think Award 3rd; np-OPR #1 of 4,404 worldwide (FTCScout).',
          '2022–23 "Phoenix" (Power Play): dual-arm turret on an extending drivetrain, 13 ft scoring radius. Worlds Ochoa Division Finalist + Innovate Award. See the dedicated project.',
          '2023–24 "Athena" (Centerstage): tilting belted elevator on lead screws, two-pixel compliant scorer, rail-launched drone. FiT-North Area Champion + Control Award; ftcstats qualifier rank #1.',
          '2024–25 "Nautilus" (Into the Deep): sprung claw designed for wall pickup and passive chamber clipping. Worlds Franklin division rank 14, Connect Award; FiT-North Regional Winner + Control.',
          '2025–26 "Rebound" (Decode): wedge spindexer, sprung-cam hammer, flywheel with telescoping hood on a 200 Hz servo turret — three sorted balls in under half a second. Worlds Goodall Division Winner → FIRST Championship Finalist Alliance.',
        ]},
        { heading: 'Results by season', bullets: [
          '2021–22: 60–5–0. Alabama State champion + Inspire; TX-North Regional champion + Innovate; Worlds Jemison division #2, Think Award 3rd. np-OPR #1 of 4,404.',
          '2022–23: 61–22–0. TX-North Regional champion + Innovate; Texas State Finalist + Connect; Worlds Ochoa Division Finalist + Innovate. np-OPR #10 of 5,671.',
          '2023–24: 41–3–0. Undefeated league play; U² Tournament winner + Inspire; Area Champion + Control; TX State division finalist; Maryland Tech Invitational finalist. np-OPR #9 worldwide, #1 in Texas.',
          '2024–25: 50–18–2. Early Bird winner + Think; FiT-North Regional Champion (captain) + Control; Worlds Franklin division #14, Connect Award.',
          '2025–26: 33–25–0. Regional division finalist; Worlds Goodall Division Winner; FIRST Championship Finalist Alliance.',
        ]},
        { heading: 'Leadership', bullets: [
          'Reviewed 85 applications, ran 40 interviews, and onboarded 13 new members.',
          'Ran a summer design camp with 200+ participants; attendees went on to become 2025 Worlds division winners.',
          'Recovered from grabber and drive-module failures mid-event (Dec 2024) to win from rank 10 of 24.',
          'Set up the team\'s 501(c)(3).',
        ]},
      ],
      images: [
        { src: 'assets/img/ftc7172/01-rebound-2026.jpg', alt: 'Rebound, the 2025-26 Decode robot', caption: '"Rebound" (2025–26 Decode) — World Championship Finalist Alliance' },
        { src: 'assets/img/ftc7172/02-phoenix-2023.jpg', fit: 'contain', alt: 'Phoenix, the 2022-23 Power Play robot', caption: '"Phoenix" (2022–23 Power Play) — dual-arm turret on extending drivetrain' },
        { src: 'assets/img/ftc7172/03-nautilus-2025.jpg', alt: 'Nautilus, the 2024-25 Into the Deep robot', caption: '"Nautilus" (2024–25 Into the Deep) — sprung claw for wall pickup' },
        { src: 'assets/img/ftc7172/04-defiant-2022.jpg', alt: 'Defiant, the 2021-22 Freight Frenzy robot', caption: '"Defiant" (2021–22 Freight Frenzy) — butterfly drivetrain, intl. rank #1' },
      ],
      links: [
        { label: 'ftc7172.org', href: 'https://www.ftc7172.org' },
        { label: 'All stats (FTCScout)', href: 'https://ftcscout.org/teams/7172' },
        { label: 'FIRST blog — 2026 Finalist Alliance', href: 'https://community.firstinspires.org/congratulations-to-our-decode-first-championship-teams' },
        { label: 'YouTube', href: 'https://www.youtube.com/channel/UCAqfGNnORI9ZZcjtNGsgPvQ' },
        { label: 'Behind the Bot — Power Play (FUN)', href: 'https://youtu.be/HBBmBNJ_7LY' },
      ],
    },
    {
      id: 'drone-launcher',
      cardImage: 3,
      title: 'Paper-Airplane "Drone" Launcher — FTC Centerstage',
      date: '2023 – 2024',
      role: 'Designer',
      featured: true,
      categories: ['Robotics', 'CAD'],
      tags: ['Fusion 360', 'Constant-force', 'Linear rail', 'Aerodynamics', 'Rapid prototyping'],
      summary: 'A surgical-tubing launcher that snapped at the State Championship became a tension-free constant-force design that hit Zone 1 in 8 of 10 matches at the Maryland Tech Invitational.',
      facts: [
        { label: 'Versions', value: '3 launcher + dozens of plane folds' },
        { label: 'Accuracy', value: 'Zone 1 in 8/10 matches (MTI)' },
        { label: 'Award', value: 'Hardware Mastery · Finalist Alliance 1st pick' },
      ],
      sections: [
        { heading: 'Problem', text: 'Centerstage scored a paper airplane launched over the field wall into one of three zones. V1 used stretched surgical tubing to accelerate a carriage on a linear rail. It was consistent in testing, but consistency degraded as the tubing tension drifted — and while re-tensioning at the State Championship, the mechanism snapped in half.' },
        { heading: 'Design', bullets: [
          'Redesigned after States around a mechanism that needs no re-tensioning (inspired by team 17315 Tomahawk). First prototype was built at home while out with Covid.',
          'Planes needed slightly negative static stability so they stall and settle into the zone rather than glide past it; ±0.5 mm fold variance was enough to change the landing, so each plane was hand-tuned over hundreds of launches.',
          'Ran structured testing: launch, mark landing, compare accuracy and precision across fold patterns and launcher versions.',
        ]},
        { heading: 'Outcome', text: 'At the Maryland Tech Invitational (40-team invitational at JHU APL) the launcher scored Zone 1 in 8 of 10 matches, Zone 2 once, and missed once on a timing error — contributing to Finalist Alliance 1st Pick and the Hardware Mastery Award.' },
      ],
      images: [
        { src: 'assets/img/launcher/01-final-cad.jpg', fit: 'contain', alt: 'Final launcher CAD render', caption: 'Final design — no re-tensioning required' },
        { src: 'assets/img/launcher/02-v1-surgical-tubing-cad.jpg', alt: 'V1 launcher CAD with surgical tubing', caption: 'V1 — surgical tubing on a linear rail' },
        { src: 'assets/img/launcher/03-rail-cad.jpg', alt: 'Launcher carriage on rail CAD', caption: 'Carriage + rail iteration' },
        { src: 'assets/img/launcher/04-prototype-a.jpg', alt: 'Hand-held blue prototype', caption: 'First printed prototype' },
        { src: 'assets/img/launcher/05-prototype-b.jpg', alt: 'Prototype rear view', caption: 'Prototype, rear' },
        { src: 'assets/img/launcher/06-landing-zones.jpg', alt: 'Landing zone scatter diagram', caption: 'Landing-zone test results' },
      ],
      links: [
        { label: 'V1 testing video', href: 'https://www.youtube.com/watch?v=RNoj_P2VNBY' },
        { label: 'V2 initial testing', href: 'https://drive.google.com/file/d/1WoOeyi_kb7Gg0BDK5wNNIA0lv1Q3RA16/view' },
      ],
    },
    {
      id: 'master-sketches',
      title: 'Master-Sketch-Driven CAD',
      date: '2022 – 2026',
      role: 'CAD workflow',
      categories: ['CAD'],
      tags: ['Fusion 360', 'Parametric', 'Top-down design', 'Onshape'],
      summary: 'Evolving from one crowded master sketch that only I could edit to layered sketches that let teammates change a mechanism by editing a handful of dimensions.',
      sections: [
        { heading: 'V1 — one sketch to rule them all', text: 'For the first Valkyrie scoring extension, a single master sketch controlled most features in the mechanism: change one dimension or constraint and the whole model followed. It worked — but it got so crowded it became hard for me and impossible for anyone else.' },
        { heading: 'V2 — layered sketches', text: 'For the next version I split control across four sketches: one for the basic dimensions and position, and one each for the inner/outer side plates and the belt-and-pulley idlers. Much cleaner, and teammates could actually work with the model.' },
        { heading: 'Now', text: 'The master sketch for our Decode-season ball shooter and transfer is deliberately simple — the lesson is that the sketch exists to be read by other people, not to be clever.' },
      ],
      images: [
        { src: 'assets/img/sketches/01-shooter-cad.jpg', fit: 'contain', alt: 'Ball shooter turret CAD render', caption: 'Decode ball shooter — driven by the sketch below' },
        { src: 'assets/img/sketches/02-valkyrie-v1-sketch.jpg', alt: 'Crowded V1 master sketch', caption: 'V1 master sketch — fully constrained, unreadable' },
        { src: 'assets/img/sketches/03-layered-sketch.jpg', alt: 'Layered scoring extension sketch', caption: 'V2 — four layered sketches' },
        { src: 'assets/img/sketches/04-shooter-sketch.jpg', alt: 'Ball shooter geometry sketch', caption: 'Shooter wheel geometry sketch' },
        { src: 'assets/img/sketches/05-arm-profile-sketch.jpg', alt: 'Arm profile sketch', caption: 'Arm profile sketch' },
      ],
    },
    {
      id: 'rocketry',
      title: 'Fully 3D-Printed Model Rockets',
      date: '2023 – 2026',
      role: 'Rocketry Club founder & president',
      categories: ['Aerospace', 'CAD'],
      tags: ['Onshape', 'OpenRocket', '3D printing', 'Afinia H+1', 'Stability'],
      summary: 'Founded the club to build and fly rockets from whatever we had — mostly an Afinia H+1 printer. Air, water, and solid-fuel rockets; some came down too fast, one never came down.',
      sections: [
        { heading: 'Design', bullets: [
          'Printed airframes and fins modeled in Onshape, flight-simulated in OpenRocket.',
          'Adjustable nose-weight compartment on a rotational dovetail slider to tune static stability without reprinting.',
        ]},
        { heading: 'Failures', text: 'Parachute failures (came down too fast), launch failures, and one rocket that went into the clouds and was never seen again. Each one fed the next print.' },
      ],
      images: [
        { src: 'assets/img/rocketry/01-printed-sections.jpg', alt: 'Printed rocket sections laid out', caption: 'Printed airframe sections' },
        { src: 'assets/img/rocketry/02-assembled.jpg', alt: 'Assembled rocket standing upright', caption: 'Assembled' },
        { src: 'assets/img/rocketry/03-onshape.jpg', alt: 'Onshape rocket assembly', caption: 'Onshape assembly' },
        { src: 'assets/img/rocketry/04-openrocket.jpg', alt: 'OpenRocket simulation', caption: 'OpenRocket flight simulation' },
      ],
      links: [
        { label: 'Launch videos', href: 'https://drive.google.com/drive/folders/111P74FA-54lxr2Gh_t-UcjrSUF1K22-_' },
      ],
    },
    {
      id: 'telescope',
      cardImage: 2,
      title: '3D-Printed Telescope',
      date: '2025',
      role: 'With David (Physics 2)',
      categories: ['CAD'],
      tags: ['Fusion 360', 'Optics', 'Carbon fiber rods', '3D printing'],
      summary: 'Assigned a ray diagram of a telescope, we built one instead — printed lens clamps on carbon-fiber rods, and a crash course in why identical lenses don\'t compound.',
      sections: [
        { heading: 'Design', bullets: [
          'Carbon-fiber rods for stiffness; printed ring clamps slide along them so lens spacing is adjustable.',
          'Clamp slit sized for different lens types (concave, convex); loosen screws to reposition.',
        ]},
        { heading: 'What we learned', text: 'We expected stacking lenses to compound magnification. It doesn\'t — magnification comes from the focal-length difference between objective and eyepiece, and ours were identical. Fix: stack several lenses close together to emulate a shorter focal length, then place one further away. The final image was blurry (chromatic aberration) and inverted (no erecting lens), and it briefly worked better as a microscope. Presented at the Spark STEM outreach program.' },
      ],
      images: [
        { src: 'assets/img/telescope/01-truss-cad.jpg', alt: 'Telescope tube truss with printed lens clamps', caption: 'Telescope tube — printed lens clamps sliding on carbon-fibre rods' },
        { src: 'assets/img/telescope/02-clamp-cad.jpg', alt: 'Lens clamp bracket CAD', caption: 'Lens clamp' },
        { src: 'assets/img/telescope/03-truss-photo.jpg', alt: 'Carbon rod truss with printed rings', caption: 'Printed rings on carbon rods' },
        { src: 'assets/img/telescope/04-assembly.jpg', alt: 'Assembling the telescope in class', caption: 'Assembly' },
      ],
    },
    {
      id: 'fusion-scripts',
      aiUse: 'claude',
      title: 'Fusion 360 Automation Scripts',
      date: '2023 – present',
      role: 'Solo project',
      categories: ['CAD', 'Software'],
      tags: ['Fusion 360 API', 'Python', 'Thread features', 'Parametric', 'Sketch geometry', 'Workflow'],
      summary: 'Two scripts that replace the CAD I kept redoing by hand every robot iteration: a REV 15 mm extrusion generator built from eighth-profile symmetry, and an M3 screw generator that models real threads, a hex socket, and a chamfered tip from two prompts.',
      facts: [
        { label: 'Scripts', value: '2 — Extrusion (215 lines) and M3 Screw Create (309 lines)' },
        { label: 'Most-used', value: 'M3 Screw Create — screws outnumber extrusion profiles per robot' },
        { label: 'Time saved', value: 'roughly 3–5 minutes per part (estimate)' },
        { label: 'Status', value: 'Both work; the extrusion script is brittle on profile selection' },
      ],
      sections: [
        { heading: 'REV extrusion generator', text: 'Every FTC frame member uses the same REV 15 mm cross-section — center bore, four corner bores, and a repeating slot pattern — which is tedious to sketch by hand. The script builds one-eighth of the profile from coordinate arrays of lines and arcs, then mirrors it across both axes and the diagonal to close it, prompts for a length validated through the units manager, and extrudes into a new component.' },
        { heading: 'M3 screw generator', text: 'FTC robots use dozens of M3 screws in varying lengths and head styles, which was the biggest repeated time sink. The script asks socket-head vs button-head (ISO 4762 / ISO 7380 dimensions), prompts for a validated length, then builds the part: revolved head profile, extruded shank, modeled M3 threads via recommendThreadData and createThreadInfo, a tapered-extrude hex socket cut, a chamfered tip, and a black appearance pulled from the appearance library. It names the component — "M3x10 socket head screw" — and handles Part-design documents that will not allow new components.' },
        { heading: 'What the API taught me', bullets: [
          'Sketch geometry is pure coordinate math — exploiting the extrusion profile\'s 8-fold symmetry cut the data entry to a fraction of the full outline.',
          'Selecting a profile by index is fragile: the correct profile depends on geometry creation order. Selecting by largest area is far more robust, which is why the screw script survives edits and the extrusion script does not.',
          'The thread API beats hard-coding thread designations — recommendThreadData returns the right data for the diameter instead of me maintaining a table.',
          'API defensiveness matters: appearance library names differ between Fusion versions, so the lookup has to fail gracefully.',
        ]},
      ],
      images: [
        { src: 'assets/img/fusion-scripts/01-robot-render.jpg', fit: 'contain', alt: 'FTC robot render showing REV extrusion in use', caption: 'Where the generated parts end up — REV extrusion and M3 hardware throughout the frame' },
      ],
      links: [
        { label: 'Extrusion script demo', href: 'https://drive.google.com/file/d/18fCxM1h6V8WSYh84AdAiBbvuGsqVMpSP/view' },
      ],
    },

  ],

  /* ---------------- CAD GALLERY ----------------
     Either reference a project image ({project, index}) or give a standalone {src, caption, tool}. */
  gallery: [
    { project: 'dual-arm-robot', index: 0, tool: 'Fusion 360' },
    { project: 'rebound', index: 0, tool: 'Fusion 360' },
    { project: 'defiant', index: 0, tool: 'Fusion 360' },
    { project: 'nautilus', index: 0, tool: 'Fusion 360' },
    { project: 'dual-arm-robot', index: 7, tool: 'Fusion 360' },
    { project: 'rebound', index: 2, tool: 'Fusion 360' },
    { project: 'nautilus', index: 4, tool: 'Fusion 360' },
    { project: 'defiant', index: 4, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 0, tool: 'Fusion 360' },
    { project: 'rebound', index: 3, tool: 'Fusion 360' },
    { project: 'defiant', index: 2, tool: 'Fusion 360' },
    { project: 'nautilus', index: 1, tool: 'Fusion 360' },
    { project: 'dual-arm-robot', index: 16, tool: 'Fusion 360' },
    { project: 'rebound', index: 5, tool: 'Fusion 360' },
    { project: 'telescope', index: 0, tool: 'Fusion 360' },
    { project: 'nautilus', index: 2, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 1, tool: 'Fusion 360 sketch' },
    { project: 'rocketry', index: 2, tool: 'Onshape' },
    { project: 'rebound', index: 9, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 2, tool: 'Fusion 360 sketch' },
    { project: 'dual-arm-robot', index: 15, tool: 'Fusion 360' },
    { project: 'master-sketches', index: 3, tool: 'Fusion 360 sketch' },
    { src: 'assets/img/misc/differential-swerve.jpg', alt: 'Differential swerve module CAD', caption: 'Differential swerve module — off-season study', tool: 'Fusion 360' },
  ],

  /* ---------------- EXPERIENCE ---------------- */
  experience: [
    { role: 'Hypersonics Student Researcher', org: 'Georgia Tech VIP Program', date: 'Aug 2026 – present', bullets: ['Vertically Integrated Projects research team, Atlanta, GA.'] },
    { role: 'Co-Founder', org: 'Hardpoint Robotics', date: 'May 2026 – present', bullets: ['Designing and building NDAA-compliant development UAVs; FAA Part 107 certified.', 'Airframe CAD, CF-Nylon printed parts, vendor-manufactured carbon-fiber structure.'] },
    { role: 'Engineering Design Intern', org: 'SWYFT Robotics', date: 'May 2025 – May 2026', bullets: ['Sprockets, gears, pulleys, and a modular robot cart for FIRST teams.', 'Low-cost manufacturing via extrusion and fiber-laser cutting.'] },
    { role: 'Captain & Lead Designer', org: 'FTC Team 7172 Technical Difficulties', url: 'https://ftc7172.org', date: 'Sep 2021 – May 2026', bullets: ['Finalist Alliance at the 2026 FIRST Championship; four World Championship appearances; #1 np-OPR worldwide in 2021–22.', '245–73–2 in qualification matches over five seasons, 19 event wins, 63 awards including Inspire, Think, Connect, Innovate, Design, and Control awards.', 'Mechanisms: linkages, counter-springing, pulley systems, geartrains, 6-DOF arms.', 'Reviewed 85 applications, ran 40 interviews, and onboarded 13 new members; set up the team\'s 501(c)(3).'] },
    { role: 'Student, UAS-SAR', org: 'MIT Beaver Works Summer Institute', date: 'Jun – Aug 2024', bullets: ['Synthetic aperture radar imaging from a DJI F550 with a PulsON 440 radar.'] },
    { role: 'Founder & President', org: 'Rocketry Club', date: 'Mar 2023 – May 2026', bullets: ['Designed, printed, flew, and frequently crashed model rockets.'] },
    { role: 'Co-Captain', org: 'Academic Decathlon', date: 'Sep 2023 – May 2026', bullets: ['2nd at State; gold in mathematics.'] },
    { role: 'B.S. Aerospace Engineering', org: 'Georgia Institute of Technology', date: '2026 – 2029', bullets: [] },
    { role: 'High School Diploma', org: 'School of Science and Engineering, Dallas TX', date: '2022 – 2026', bullets: ['3.97 UW GPA · Rank 2 · 1600 SAT · National Merit Scholar · NASA High School Aerospace Scholar.'] },
  ],

  /* ---------------- SKILLS ---------------- */
  skills: [
    { group: 'CAD & Manufacturing', items: ['Fusion 360', 'Onshape', 'SolidWorks', 'Autodesk Inventor (certified)', 'FEA', 'Master sketches', '3D printing', 'CF-Nylon', 'Laser cutting', 'CNC', 'DFM'] },
    { group: 'Robotics & Embedded', items: ['NVIDIA Jetson', 'ROS 2 / Nav2', 'RTAB-Map', 'ArduPilot', 'Arduino', 'Raspberry Pi', 'REV Control Hub', 'OpenCV', 'AprilTag', 'RealSense / T265'] },
    { group: 'Programming', items: ['Python', 'NumPy', 'Pandas', 'Matplotlib', 'TensorFlow', 'JavaScript', 'HTML/CSS', 'SQL', 'Git'] },
    { group: 'Aerospace', items: ['UAV airframe design', 'FAA Part 107', 'OpenRocket', 'Synthetic aperture radar', 'Trajectory modeling'] },
  ],
};
